### ISSUE TITLE
[Feature request] Redesign the interface to have a single window with increased font size, with an option to copy games file before listing excecutables.

### ISSUE THREAD

**Issue by malnaanah** [ruanformigoni/gameimage#100]
First I would like to say that the application is amazing and I hope the following redesign would be considered:
1- Having one window for the app, with messages at the bottom and options at the top.
2- increasing the font size because it is hardly readable.
3- Give option, after creating the game folder and before listing the executable, that ask the user to copy any game files inside window folder. Currently the user have to copy the game files then go to the previous menu and back to the executables menu to refresh the list and display the excecutables in the newly copied game files.

Regards.

**Comment by ruanformigoni** [comment]
Hi @malnaanah , thank you for the suggestions!

> 1- Having one window for the app, with messages at the bottom and options at the top.

You mean to merge the logger window with the main window in the wizard? That is something I wanted to do, but it was not trivial.

> 2- increasing the font size because it is hardly readable.

I have increased the font size (for the next release), but could you provide a screenshot of how it looks currently on your side? 

> 3- Give option, after creating the game folder and before listing the executable, that ask the user to copy any game files 

You can copy the files with the file manager (opened by the folder icon by the side of the executable path), I think that having an extra frame just to open the WINEPREFIX directory would be a bit redundant. Another solution would be to detect newly copied files and auto-update the GUI to show them. I'll give this some thought.

**Comment by malnaanah** [comment]
I guess having an icon to refresh the executable file list is a good option.

This is how the application appear on my desktop, the resolution is 1368x768

![Screenshot_20241008_232516](https://github.com/user-attachments/assets/d801818a-a600-4a05-83be-79bca7276df8)

**Comment by ruanformigoni** [comment]
Ok, thanks! Another thing that is fixed in the next version is scaling, the 'prev' and 'next' buttons are looking weird in there because of that.

**Comment by ruanformigoni** [comment]
> 2- increasing the font size because it is hardly readable.

Implemented in `v1.4.0`.

> 3- Give option, after creating the game folder and before listing the executable, that ask the user to copy any game files inside window folder. Currently the user have to copy the game files then go to the previous menu and back to the executables menu to refresh the list and display the excecutables in the newly copied game files.

Refresh button included in the executables frame to remedy this issue.
