### ISSUE TITLE
DXVK doesnt download

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#102]
Log file when trying to install DXVK

I :: [o]: [wine.sh] Downloading https://web.archive.org/web/2000/https://github.com/doitsujin/dxvk/releases/download/v/dxvk-.tar.gz to /home/gameimage/.cache/winetricks/dxvk
I :: [o]: [wine.sh] wget: unrecognized option: read-timeout
I :: [o]: [wine.sh] BusyBox v1.37.0.git (2024-10-03 00:49:37 UTC) multi-call binary.
I :: [o]: [wine.sh]
I :: [o]: [wine.sh] Usage: wget [-cqS] [--spider] [-O FILE] [-o LOGFILE] [--header STR]
I :: [o]: [wine.sh] 	[--post-data STR | --post-file FILE] [-Y on/off]
I :: [o]: [wine.sh] 	[--no-check-certificate] [-P DIR] [-U AGENT] [-T SEC] URL...
I :: [o]: [wine.sh]
I :: [o]: [wine.sh] Retrieve files via HTTP or FTP
I :: [o]: [wine.sh] 
I :: [o]: [wine.sh] 	--spider	Only check URL existence: $? is 0 if exists
I :: [o]: [wine.sh] 	--header STR	Add STR (of form 'header: value') to headers
I :: [o]: [wine.sh] 	--post-data STR	Send STR using POST method
I :: [o]: [wine.sh] 	--post-file FI
I :: [o]: LE	Send FILE using POST method
I :: [o]: [wine.sh] 	--no-check-certificate	Don't validate the server's certificate
I :: [o]: [wine.sh] 	-c		Continue retrieval of aborted transfer
I :: [o]: [wine.sh] 	-q		Quiet
I :: [o]: [wine.sh] 	-P DIR		Save to DIR (default .)
I :: [o]: [wine.sh] 	-S    		Show server response
I :: [o]: [wine.sh] 	-T SEC		Network read timeout is SEC seconds
I :: [o]: [wine.sh] 	-O FILE		Save to FILE ('-' for stdout)
I :: [o]: [wine.sh] 	-o LOGFILE	Log messages to FILE
I :: [o]: [wine.sh] 	-U STR		Use STR for User-Agent header
I :: [o]: [wine.sh] 	-Y on/off	Use proxy
I :: [o]: [wine.sh] ------------------------------------------------------
I :: [o]: [wine.sh] warning: Downloading https://web.archive.org/web/2000/https://github.com/doitsujin/dxvk/releases/download/v/dxvk-.tar.gz failed
I :: [o]: [wine.sh] ------------------------------------------------------
I :: [o]: [wine.sh] Winetricks log  : /media/ade/Temp/Temp/build/Ghosts-n-Goblins-Resurrection/opt/gameimage-games/Ghosts-n-Goblins-Resurrection/wine/winetricks.log

**Comment by ruanformigoni** [comment]
Hi @Blad3forc3 thanks for reporting this issue, I'll try to replicate from my side. You do not need to install dxvk or vkd3d if you are using umu-proton, since it is already included.

**Comment by ruanformigoni** [comment]
Fixed in the runners, re-downloading the files to a clean build directory. Thanks again!
