### ISSUE TITLE
Logfile flooded with gstreamer error

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#103]
Failed to load plugin '/opt/wine/files/lib64/gstreamer-1.0/libgsty4mdec.so': /opt/wine/files/lib64/gstreamer-1.0/libgsty4mdec.so: wrong ELF class: ELFCLASS64

**Comment by ruanformigoni** [comment]
Thanks for reporting this issue @Blad3forc3 , is this on umu? Also, is this during the installation of something specific with winetricks, or just runing an executable?

**Comment by Blad3forc3** [comment]
Yes i am using umu with no additional winetricks verbs installed

**Comment by ruanformigoni** [comment]
@Blad3forc3 is there a GOG or abandonware game that presents this issue? It did not happen to me with the games I tested.

**Comment by Blad3forc3** [comment]
I think this error may have something to do with UMU

**Comment by ruanformigoni** [comment]
Confirmed to be an issue with wine UMU.
