### ISSUE TITLE
No flatimage created

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#104]
After going through the process to create a flatimage, there is nothing saved
I have this in the logfile after compression

Packaged Halo-Combat-Evolved
Created directory /media/ade/Temp/gameimage/build/Halo-Combat-Evolved/opt/gameimage-games/Halo-Combat-Evolved/icon
Resized image '/media/ade/Temp/gameimage/build/Halo-Combat-Evolved/opt/gameimage-games/Halo-Combat-Evolved/icon/icon.wizard.resized.png'
Created directory /media/ade/Temp/gameimage/build/Halo-Combat-Evolved/opt/gameimage-games/Halo-Combat-Evolved/icon
Resized image '/media/ade/Temp/gameimage/build/Halo-Combat-Evolved/opt/gameimage-games/Halo-Combat-Evolved/icon/icon.wizard.resized.png'
Integration items: mimetype,icon
Dispatch command: "/opt/gameimage/bin/gameimage-cli" : ["desktop", "Halo Combat Evolved", "/media/ade/Temp/gameimage/halo.png", "mimetype,icon"]
I :: Open file '"/media/ade/Temp/gameimage/build/gameimage.json"' as READ
I :: Reading image from "/media/ade/Temp/gameimage/halo.png"
I :: Reading as 'png'
I :: PATH: Check for "/opt/gameimage/bin/magick"
I :: PATH: Found '"/opt/gameimage/bin/magick"
I :: Spawn command: /opt/gameimage/bin/magick,/media/ade/Temp/gameimage/halo.png,-resize,300x450,/media/ade/Temp/gameimage/build/Halo-Combat-Evolved/opt/gameimage-games/Halo-Combat-Evolved/cropped.png
I :: Image width and height 300x300
I :: Target width and height 300x450
I :: Difference: -150
I :: Adjusted width and height to 150x300
I :: Writing image to "/media/ade/Temp/gameimage/build/Halo-Combat-Evolved/opt/gameimage-games/Halo-Combat-Evolved/desktop.png"
I :: Open file '"/media/ade/Temp/gameimage/build/Halo-Combat-Evolved/opt/gameimage-games/Halo-Combat-Evolved/desktop.json"' as CREATE
I :: Creating db file '"/media/ade/Temp/gameimage/build/Halo-Combat-Evolved/opt/gameimage-games/Halo-Combat-Evolved/desktop.json"
I :: Spawn command: /fim/static/fim_portal,/media/ade/Temp/gameimage/build/wine.flatimage,fim-desktop,setup,/media/ade/Temp/gameimage/build/Halo-Combat-Evolved/opt/gameimage-games/Halo-Combat-Evolved/desktop.json
I :: Spawn command: /fim/static/fim_portal,/media/ade/Temp/gameimage/build/wine.flatimage,fim-desktop,enable,MIMETYPE,ICON
Finished desktop configuration

No flatimage saved in the location it says

I have a halo-combat-evolved.layer in the output dir that is the size i would expect the finished flatimage but no flatimage

**Comment by Blad3forc3** [comment]
Close this. I was expecting the saved flatimage to be put into the build directory somewhere but it has saved it in a old location

**Comment by ruanformigoni** [comment]
No problem! I'm happy it worked out :smile:
