### ISSUE TITLE
Iconsize changed?

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#106]
Has the icon size for the finished flatimage changed?
I used to have 512x512 icons that were fine but are now being "chopped off" as if they were 600x900?

**Comment by ruanformigoni** [comment]
Yes, the image is zoomed in to fit the frame if it does not fit in it.

**Comment by Blad3forc3** [comment]
The old gameimage used to accomodate round icons for finished flatimages. Is this not possible now?

**Comment by ruanformigoni** [comment]
Could you share what it looks like currently, just to make sure it is not a bug? The target image and the result.

**Comment by Blad3forc3** [comment]
Picture of the icon with the finished flatimage on the right after selecting the round icon as the main image
![Screenshot_20241018_165439](https://github.com/user-attachments/assets/992bbb5a-8230-4fce-8a77-e4f86ac79c27)

**Comment by ruanformigoni** [comment]
You can use `magick -background none -gravity center -extent 600x900 halo.png halo-out.png`, and then select `halo-out.png` as a background, which should resolve this issue.

**Comment by ruanformigoni** [comment]
I'll include an option to select the cropping mode of the image in the next version, in case you want to fit the width, instead of the full frame like in this example.
