### ISSUE TITLE
mime type and file association still active.

### ISSUE THREAD

**Issue by malnaanah** [ruanformigoni/gameimage#109]
I made Aladdin 3D flatimage in version 1.4.1, the GUI runs but the game doesn't, i have this error:

./Aladdin-3D-X2.flatimage 
I :: Open file '"/opt/gameimage-games/Aladdin-3D/gameimage.env.json"' as READ
I :: Could not set environment: Failed to open '/opt/gameimage-games/Aladdin-3D/gameimage.env.json'
I :: FlatImage distribution: ARCH
I :: Open file '"/opt/gameimage-games/Aladdin-3D/gameimage.json"' as READ
I :: Open file '"/opt/gameimage-games/Aladdin-3D/gameimage.json"' as READ
I :: Open file '"/opt/gameimage-games/Aladdin-3D/gameimage.wine.args.json"' as READ
I :: Optional (caught): Failed to open '/opt/gameimage-games/Aladdin-3D/gameimage.wine.args.json'
I :: No arguments for "wine/drive_c/Aladdin Nasira's Revenge Pc Repack/aladdin.exe"
I :: Spawn command: /opt/wine/bin/wine.sh,/opt/gameimage-games/Aladdin-3D/wine/drive_c/Aladdin Nasira's Revenge Pc Repack/aladdin.exe
I :: [o]: I :: Invalid environment variable 'PROFILEHOME='
I :: [o]: I :: execve() failed: No such file or directory
 

Also, I deactivated creating start menu icon, there is no start menu icon but the mime types, file association and app icon is still active and that that clutters the system and messes with my custom KDE service menu. I think these configurations should be optional and disabled by default. 

Regards,

**Comment by ruanformigoni** [comment]
Thanks for the feedback @malnaanah . I'll include more options to disable integrations in the wizard in `v1.4.2` and dig into this issue.

**Comment by malnaanah** [comment]
Please make no integration (just like any normal file) the default option.

**Comment by Tell-Sackett** [comment]
I have a similar issue (if not the same), it would seem. 

Decided it would be a good idea to try and re-package Tomb Raider: Anniversary, since I knew that worked well with the previous version of GameImage. Note: In case it matters, I am on Arch now (as opposed to Debian, which I was using during my last few posts).

Terminal output for the build process of the flatimage copied to the attatched file [build.txt](https://github.com/user-attachments/files/17447418/build.txt).
Terminal output for attempting to run the flatimage copied to the attatched file [run.txt](https://github.com/user-attachments/files/17447421/run.txt).

**Comment by Tell-Sackett** [comment]
Sorry, the above "run.txt" is flashing an error about XDG DESKTOP due to the fact that I am on a WM without properly setting those environment variables.

I properly set them and here is the updated output of [run.txt](https://github.com/user-attachments/files/17447680/run.txt).

**Comment by ruanformigoni** [comment]
Hello! It is now possible to completely disable the desktop integration, just uncheck both checkboxes at the desktop screen and it will not create any icon, mimetype or desktop entry. About the issue with Tomb Raider, it worked for me with umu, does it fail during test as well?

**Comment by ruanformigoni** [comment]
I'm going to close this one as the file association issue, and track the problems with umu in https://github.com/ruanformigoni/gameimage/issues/112
