### ISSUE TITLE
FlatImages consumes huge amount of memory

### ISSUE THREAD

**Issue by malnaanah** [ruanformigoni/gameimage#115]
Not sure if this is how flatimages works. But I have a flatimage for Command and Conqure zero hour and it consumes 2 GB of ram when it runs. Is this normal. When use wine that is installed using apt it only consumes about 400 MB of ram.

**Comment by ruanformigoni** [comment]
FlatImage itself has low overhead. This might be introduced by [bubblewrap](https://github.com/containers/bubblewrap) to containerize applications, and having to load several libraries into memory that you already have installed on the host (but might have differing versions and be incompatible with your game).
