### ISSUE TITLE
No dekstop icon saved in finished gameimage

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#116]
With the latest gameimage there is no desktop icon saved in the gameimage. If this is by design how can I inject a desktop icon into the gameimage?

**Comment by ruanformigoni** [comment]
Hi @Blad3forc3 , thanks for reporting this issue. It is still working as before on my side, did you leave both boxes checked at the end of the wizard?

**Comment by Blad3forc3** [comment]
You are correct Ruan. I had the top one of the two unchecked.

**Comment by Blad3forc3** [comment]
Just one question on this, can you inject an icon into an already created flatimage?

**Comment by ruanformigoni** [comment]
Yes, you can use [fim-desktop](https://flatimage.github.io/docs/cmd/desktop/) for that.

**Comment by Blad3forc3** [comment]
I'm trying to inject an icon into an existing flatimage i created and it errors with this..
Program exited with error: Could not determine enum entry from './CC4.PNG'

**Comment by Blad3forc3** [comment]
Hi Ruan,
Could you write the exact command to inject a missing desktop icon for a flatimage?

**Comment by ruanformigoni** [comment]
Hi @Blad3forc3 , it's `/app.flatimage fim-desktop setup ./desktop.json`, where the desktop.json file is:

```


{
  "name": "MyApp",
  "icon": "/path/to/icon.png",
  "categories": ["Game"]
}
```

**Comment by ruanformigoni** [comment]
Yes, that is the help message of flatimage versions previous to 1.0.0.

**Comment by ruanformigoni** [comment]
I would recommend updating if possible.
