### ISSUE TITLE
Add custom wine versions

### ISSUE THREAD

**Issue by chicco-carone** [ruanformigoni/gameimage#12]
I think it would be a great idea to add the ability to use custom wine version. For example i wanted to use this to make an appimage for osu on the steam deck and it would be better to use wine-osu (build of wine for osu). Even other games would benefit that need some specific wine versions. Maybe it can pull them locally or from github on the relase page for some wine or proton versions

**Comment by ruanformigoni** [comment]
Hi @chicco-carone , thanks for the suggestion! You can select other wine distributions as described [here](https://gitlab.com/formigoni/gameimage#select-wine-distribution), the available wine appimages are [here](https://github.com/ruanformigoni/wine). Do you have specific versions of it that you'd like to see included, besides the ones listed? Also could you provide a link for `wine-osu`.

**Comment by chicco-carone** [comment]
https://github.com/NelloKudo/WineBuilder/releases/download/wine-osu-stable-7.16/wine-osu-7.16-x86_64.tar.xz

**Comment by chicco-carone** [comment]
probably northstar proton to make an appimage for titanfall 2. its on proton up qt if you need the link

**Comment by chicco-carone** [comment]
On other idea could be to bundle in the appimage some dependencies and probably something for the mime. Now I'm just saying stuff but I really don't know if it's possible. If it is it would be great. For example still for osu there are two wine libraries to make it work (libxcomposite and gnutls) and for the mime there is a program (like a dependency) to use to make osu read .osr files.

**Comment by ruanformigoni** [comment]
Included additional wine versions, you can select them in the GUI. If there is a library missing let me know, so I can include it in the flatimage.
