### ISSUE TITLE
Make downloading the wine.flatimage and version of wine.layer optional?

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#120]
Would it be possible to make the download of wine.flatimage and *wine version*.layer optional?
It randomly downloads new ones
Sometimes the download is very slow
It seems to take a while to validate the checksums too?
Can it not just go straight to the next screen?

**Comment by ruanformigoni** [comment]
Hi @Blad3forc3 . The way that it works will change in `v1.5.0` and should match what you want.
