### ISSUE TITLE
Does the obs-gamecapture command work on created flatimages?

### ISSUE THREAD

**Issue by Blackfox-Thane** [ruanformigoni/gameimage#123]
This is more of a question rather than an issue, but could I input the `obs-gamecapture`command on a flatimage? I use the obs-vkcaoture plugin for OBS.

**Comment by ruanformigoni** [comment]
Hello! Yes, it should work without a problem. You can use it with gamescope to help avoid issues with fullscreen and OBS like this `gamescope -w 1920 -h 1080 -- ./game.flatimage --select-index 0`, assuming there is only one game in the image, if there is more you can discover their indices with `./game.flatimage --select-list`.
