### ISSUE TITLE
Couldn't fall back to Software refresh error

### ISSUE THREAD

**Issue by Blackfox-Thane** [ruanformigoni/gameimage#125]
I've trying to bundle sin gold with a native linux port dominatrix but when trying to test the binary pops up with **couldn't fall back to software refresh**

**Comment by Blackfox-Thane** [comment]
> I've trying to bundle sin gold with a native linux port dominatrix but when trying to test the binary pops up with **couldn't fall back to software refresh**

nvm i figured out that the app itself is hardcoded to a specific location so this issue is solved

**Comment by ruanformigoni** [comment]
Hi @Blackfox-Thane , good to know it worked out :smile:
