### ISSUE TITLE
wine layers other than umu-proton won't work

### ISSUE THREAD

**Issue by Blackfox-Thane** [ruanformigoni/gameimage#126]
i'm having issues trying to test and run programs with other wine layers it seems that they only work with umu-proton-ge option. also when i try to click the run/install program option on the gui it shows this error

> Dispatch command: "/opt/gameimage/bin/gameimage-cli" : ["install", "wine", "/home/thane/Downloads/windowsdesktop-runtime-8.0.7-win-x86.exe"]
I :: Open file '"/media/game-drive/Gameimage/build/gameimage.json"' as READ
I :: Open file '"/media/game-drive/Gameimage/build/gameimage.json"' as READ
I :: application: 1964-GEPD
I :: image: "/media/game-drive/Gameimage/build/wine.flatimage"
I :: prefix: "/media/game-drive/Gameimage/build/1964-GEPD/opt/gameimage-games/1964-GEPD/wine"
I :: Spawn command: /fim/static/fim_portal,/media/game-drive/Gameimage/build/wine.flatimage,fim-exec,/opt/wine/bin/wine.sh,/home/thane/Downloads/windowsdesktop-runtime-8.0.7-win-x86.exe
I :: [o]: [wine.sh] Container   : ARCH
I :: [o]: [wine.sh] Session Type: wayland
I :: [o]: [wine.sh] $*          : /home/thane/Downloads/windowsdesktop-runtime-8.0.7-win-x86.exe
I :: [o]: [wine.sh] USER        : gameimage
I :: [o]: [wine.sh] WINEDEBUG   : fixme-all
I :: [o]: [wine.sh] HOME        : /home/gameimage
I :: [o]: [wine.sh] WINEPREFIX  : /media/game-drive/Gameimage/build/1964-GEPD/opt/gameimage-games/1964-GEPD/wine
I :: [o]: [wine.sh] glxinfo log : /media/game-drive/Gameimage/build/1964-GEPD/opt/gameimage-games/1964-GEPD/wine/glxinfo.log
I :: [o]: [wine.sh] GPU Vendor  : amd
I :: [o]: [wine.sh] GPU Device  : AMD Radeon RX 7900 XT (radeonsi, navi31, LLVM 18.1.8, DRM 3.59, 6.11.6-artix1-1)
I :: [o]: [wine.sh] OpenGL      : 4.6 (Compatibility Profile) Mesa 24.2.6-arch1.1
I :: [o]: [wine.sh] Vulkan log  : /media/game-drive/Gameimage/build/1964-GEPD/opt/gameimage-games/1964-GEPD/wine/vulkan.log
I :: [o]: [wine.sh] /opt/wine/bin/wine
I :: [o]: [wine.sh] Wine version: wine-9.7.r0.g127b7faf ( TkG Staging Esync Fsync )
I :: [o]: [wine.sh] Switched directory to: /home/thane/Downloads
I :: [o]: [wine.sh] Wine log  : /media/game-drive/Gameimage/build/1964-GEPD/opt/gam
I :: [o]: eimage-games/1964-GEPD/wine/wine.log
I :: [o]: [wine.sh] /home/thane/.local/bin/umu-run
I :: [o]: [wine.sh] Using 'umu-run'
I :: [o]: [wine.sh] [1msteamrt is up to date[0m
I :: [o]: [wine.sh] [31mERROR: [1mThe following file was not found in PROTONPATH: proton[0m
I :: [o]: [wine.sh] Traceback (most recent call last):
I :: [o]: [wine.sh]   File "/home/thane/.local/bin/umu-run/__main__.py", line 14, in <module>
I :: [o]: [wine.sh]     sys.exit(main())
I :: [o]: [wine.sh]              ^^^^^^
I :: [o]: [wine.sh]   File "/home/thane/.local/bin/umu-run/__main__.py", line 9, in main
I :: [o]: [wine.sh]     return umu_run()
I :: [o]: [wine.sh]            ^^^^^^^^^
I :: [o]: [wine.sh]   File "/home/thane/.local/bin/umu-run/umu/umu_run.py", line 837, in main
I :: [o]: [wine.sh]     command: tuple[Path | str, ...] = build_command(env, UMU_LOCAL, opts)
I :: [o]: [wine.sh]                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
I :: [o]: [wine.sh]   File "/home/thane/.local/bin/umu-run/umu/umu_run.py", line 346, in build_command
I :: [o]: [wine.sh]     raise FileNotFoundError(err)
I :: [o]: [wine.sh] FileNotFoundError: The following file was not found in PROTONPATH:

I have the full log too
[Gameimage.txt](https://github.com/user-attachments/files/17699007/Gameimage.txt)

**Comment by MRDeu** [comment]
I was about to open a thread to say so but I see I'm not the only one, I think soda was able to make it go, but I've only managed to get those two to work for me.

By the way is there any reason why we can't use Proton UMU instead of Wine UMU?

**Comment by ruanformigoni** [comment]
Hi @MRDeu  and @Blackfox-Thane , issue acknowledged. thanks for reporting this issue. Will update when fixed.

**Comment by Blackfox-Thane** [comment]
UPDATE: apparently the umu-run bin file was interrupting gameimage's wine progresses, i deleted the file from .local/bin and now its good to go

![sean-connery-the-rock](https://github.com/user-attachments/assets/88d71543-df99-427e-ac39-495597ae5923)

**Comment by ruanformigoni** [comment]
I'm happy to know it worked out :smile: If they issue persists feel free to re-open.
