### ISSUE TITLE
Weird syntax loop when trying to test or launch dosbox-x

### ISSUE THREAD

**Issue by Blackfox-Thane** [ruanformigoni/gameimage#128]
Test launching the Dosbox-X binary spits out this syntax loop

[gameimage.log](https://github.com/user-attachments/files/17789047/gameimage.log)

Also i got this notification every time i launch it

![screenshot-2024-11-17-00:33:21](https://github.com/user-attachments/assets/479a06db-5cae-4a2f-95e4-f9e94cb1931a)

**Comment by ruanformigoni** [comment]
Thanks for reporting this issue, If this is still not working on `v1.5.0` I'll include one of the suggested dependencies on the runner.
