### ISSUE TITLE
Retroarch assets

### ISSUE THREAD

**Issue by jdwininger** [ruanformigoni/gameimage#13]
Is there any way to have gameimage download and include Retroarch's assets pack during initial setup? 

If there is no way to include Retroarch's assets then may I suggest it as a feature request. It would be a nice addition to Retroarch's usability if the user needed to access the game's settings.

**Comment by jdwininger** [comment]
After looking at the shell script for Retroarch I see it decompresses the RetroArch.7z. Decompressing RetroArch.7z leaves the directory RetroArch-Linux-x86_64 with RetroArch-Linux-x86_64.AppImage.home and RetroArch-Linux-x86_64.AppImage inside. RetroArch-Linux-x86_64.AppImage is then renamed to retroarch.AppImage and unpacked. From then on all work go on with Retroarch's squashfs-root directory. This ignores the RetroArch-Linux-x86_64.AppImage.home directory when repacking the retroarch.AppImage.

It seems the .config path is hard set in the retroarch binary so I guess my above feature request might not be doable.

**Comment by ruanformigoni** [comment]
Hi @jdwininger , thanks for the feedback! I think it is doable, I can package the compressed assets in the final image, then, after the user opens the image, it can check if the assets are missing. If they are, I just copy them to the currently used config dir, e.g., `.my-game.AppImage.config`.

**Comment by ruanformigoni** [comment]
Retroarch assets included in `v0.4.6`.
