### ISSUE TITLE
New version doesnt list all exes in the prefix to select

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#132]
Hi RUan,
Ive noticed with the new version the exes arent all listed to select the main execuatble.
Ive tried going back and forwards to see if it appears but sometimes it shows and sometimes it doesn't

**Comment by ruanformigoni** [comment]
Hi @Blad3forc3 , I've identified this issue as well. Thanks for reporting!

**Comment by MRDeu** [comment]
Only works with default wine

```
ipc.rs:91: Frontend key is: 1095238181
ipc.rs:112: Closed existing message queue
search.rs:34: Finished reading messages
gameimage.rs:72: SendError { .. }
```

**Comment by ruanformigoni** [comment]
This is fixed in `v1.5.1`.

**Comment by ruanformigoni** [comment]
Does the log point out something being excluded? As in `Excluded path ...` or `Excluded directory ...`. When you duplicate, do you use the same exact name for the new file? The criteria for a file to show up is that it should be a regular file (not a symlink) and end with `.exe` (case insensitive).

**Comment by Blad3forc3** [comment]
The log does point out to excluded locations:

I :: Search directory '/media/ade/Temp/Temp/build/Civilization-V/opt/gameimage-games/Civilization-V/linux'
I :: Exclude path '"/media/ade/Temp/Temp/build/Civilization-V/opt/gameimage-games/Civilization-V/linux/Sid Meier’s Civilization V/game/steam-runtime/pinned_libs_32/libcurl.so.4"'
I :: Exclude path '"/media/ade/Temp/Temp/build/Civilization-V/opt/gameimage-games/Civilization-V/linux/Sid Meier’s Civilization V/game/steam-runtime/pinned_libs_32/libgtk-x11-2.0.so.0"'
I :: Exclude path '"/media/ade/Temp/Temp/build/Civilization-V/opt/gameimage-games/Civilization-V/linux/Sid Meier’s Civilization V/game/steam-runtime/pinned_libs_32/libcurl.so.3"'
I :: Exclude path '"/media/ade/Temp/Temp/build/Civilization-V/opt/gameimage-games/Civilization-V/linux/Sid Meier’s Civilization V/game/steam-runtime/pinned_libs_32/libGLU.so.1"'
I :: Exclude path '"/media/ade/Temp/Temp/build/Civilization-V/opt/gameimage-games/Civilization-V/linux/Sid Meier’s Civilization V/game/steam-runtime/pinned_libs_32/libcurl-gnutls.so.3"'
I :: Exclude path '"/media/ade/Temp/Temp/build/Civilization-V/opt/gameimage-games/Civilization-V/linux/Sid Meier’s Civilization V/game/steam-runtime/pinned_libs_32/libdbusmenu-gtk.so.4"'
I :: Exclude path '"/media/ade/Temp/Temp/build/Civilization-V/opt/gameimage-games/Civilization-V/linux/Sid Meier’s Civilization V/game/steam-runtime/pinned_libs_32/libdbusmenu-glib.so.4"'
I :: Exclude path '"/media/ade/Temp/Temp/build/Civilization-V/opt/gameimage-games/Civilization-V/linux/Sid Meier’s Civilization V/game/steam-runtime/pinned_libs_32/libcurl-gnutls.so.4"'
I :: Exclude path '"/media/ade/Temp/Temp/build/Civilization-V/opt/gameimage-games/Civilization-V/linux/Sid Meier’s Civilization V/game/steam-runtime/amd64/selinux"'
I :: Exclude path '"/media/ade/Temp/Temp/build/Civilization-V/opt/gameimage-games/Civilization-V/linux/Sid Meier’s Civilization V/game/steam-runtime/libcurl_compat_64/libsteam-runtime-system-libcurl.so.4"'
I :: Exclude path '"/media/ade/Temp/Temp/build/Civilization-V/opt/gameimage-games/Civilization-V/linux/Sid Meier’s Civilization V/game/steam-runtime/libcurl_compat_32/libsteam-runtime-system-libcurl.so.4"'
I :: Exclude path '"/media/ade/Temp/Temp/build/Civilization-V/opt/gameimage-games/Civilization-V/linux/Sid Meier’s Civilization V/game/steam-runtime/i386/selinux"'
I :: Exclude path '"/media/ade/Temp/Temp/build/Civilization-V/opt/gameimage-games/Civilization-V/linux/Sid Meier’s Civilization V/game/steam-runtime/pinned_libs_64/libcurl.so.4"'
I :: Exclude path '"/media/ade/Temp/Temp/build/Civilization-V/opt/gameimage-games/Civilization-V/linux/Sid Meier’s Civilization V/game/steam-runtime/pinned_libs_64/libcurl.so.3"'
I :: Exclude path '"/media/ade/Temp/Temp/build/Civilization-V/opt/gameimage-games/Civilization-V/linux/Sid Meier’s Civilization V/game/steam-runtime/pinned_libs_64/libGLU.so.1"'
I :: Exclude path '"/media/ade/Temp/Temp/build/Civilization-V/opt/gameimage-games/Civilization-V/linux/Sid Meier’s Civilization V/game/steam-runtime/pinned_libs_64/libcurl-gnutls.so.3"'
I :: Exclude path '"/media/ade/Temp/Temp/build/Civilization-V/opt/gameimage-games/Civilization-V/linux/Sid Meier’s Civilization V/game/steam-runtime/pinned_libs_64/libdbusmenu-gtk.so.4"'
I :: Exclude path '"/media/ade/Temp/Temp/build/Civilization-V/opt/gameimage-games/Civilization-V/linux/Sid Meier’s Civilization V/game/steam-runtime/pinned_libs_64/libdbusmenu-glib.so.4"'
I :: Exclude path '"/media/ade/Temp/Temp/build/Civilization-V/opt/gameimage-games/Civilization-V/linux/Sid Meier’s Civilization V/game/steam-runtime/pinned_libs_64/libcurl-gnutls.so.4"'
I :: Starting IPC for "/opt/gameimage/bin/gameimage-cli"
I :: key identifier: /opt/gameimage/bin/gameimage-cli
I :: Generated message_queue key: 1094320677
I :: Message queue id: 131076

**Comment by Blad3forc3** [comment]
Might not be related but this only started happening when the filter exe box was added. Sometime i get the exe list and the bottom half of a selection at the bottom is cut off
