### ISSUE TITLE
Wine staging not installing.

### ISSUE THREAD

**Issue by Broly1** [ruanformigoni/gameimage#134]
Wine Staging hasn't been installing since version 1.4.0. I tested it last night, and the last version that works is on GameImage 1.3.1
on some games I'm having issues with controller not been detected using caffe but it works on staginging also wide screen works on staging but not on caffe, thats why I'm trying to use staging, soda or tkg and osu doesn't even load the game.
I have a suggestion: consider opening a Telegram or Discord group so we don't flood your GitHub project with noobs issues. :) 
[gameimage.log](https://github.com/user-attachments/files/17950147/gameimage.log)

**Comment by ruanformigoni** [comment]
Hi @Broly1 , thanks for reporting this issue! I'll bump when resolved.

**Comment by ruanformigoni** [comment]
Hi @Broly1 , it should be working now. This error is normal, it tries to check if the file exist to avoid re-downloading it.

**Comment by Broly1** [comment]
> Hi @Broly1 , it should be working now, please re-download staging or tkg. This error is normal, it tries to check if the file exists to avoid re-downloading it.

Yes sir, it is working great now thank you!
