### ISSUE TITLE
Gameimage compile error

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#139]
=> ERROR [ 4/10] RUN git clone https://gitlab.com/formigoni/gameimage.git                                                                           0.5s
------
 > [ 4/10] RUN git clone https://gitlab.com/formigoni/gameimage.git:
0.230 Cloning into 'gameimage'...
0.486 fatal: could not read Username for 'https://gitlab.com': No such device or address
------
Dockerfile:19
--------------------
  17 |     # WORKDIR gameimage
  18 |     # RUN sed -i "s/TRUNK/$CI_COMMIT_TAG/" src/main.sh
  19 | >>> RUN git clone https://gitlab.com/formigoni/gameimage.git
  20 |     WORKDIR gameimage
  21 |     RUN sed -i "s/TRUNK/$CI_COMMIT_TAG/" src/main.sh
--------------------
ERROR: failed to solve: process "/bin/sh -c git clone https://gitlab.com/formigoni/gameimage.git" did not complete successfully: exit code: 128

**Comment by ruanformigoni** [comment]
Hi @Blad3forc3 , that is the old `Dockerfile` used for the gitlab builds. To manually compile use the script in `docker/flatimage-alpine.sh`, the current docker files are in the `docker` directory.

**Comment by Blad3forc3** [comment]
ok cool thanks ruan

**Comment by ruanformigoni** [comment]
No problem, I just removed these files to avoid confusion.
