### ISSUE TITLE
prefix an executable with a command

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#17]
How can I prefix wine with a command in the apprun file?

I want to add this line __GL_ExtensionStringVersion=17700

so the command looks like __GL_ExtensionStringVersion=17700 wine <executable>

**Comment by ruanformigoni** [comment]
Hi @Blad3forc3, on this line:

```sh
"$YQ" --exit-status 'tag == "!!map" or tag == "!!seq"' "$YAML" &>/dev/null || echo "cmd: \"{wine} {exec}\"" > "$YAML"
```

You can change it to:

```sh
"$YQ" --exit-status 'tag == "!!map" or tag == "!!seq"' "$YAML" &>/dev/null || echo "cmd: \"__GL_ExtensionStringVersion=17700 {wine} {exec}\"" > "$YAML"
```

**Comment by Blad3forc3** [comment]
Thanks that worked. Any chance of updating the Staging wine package to 8.2?

**Comment by ruanformigoni** [comment]
Nice, sure I just started a manual pipeline in github-ci, you can follow the progress [here](https://github.com/ruanformigoni/wine/actions/workflows/staging.yml)

**Comment by Blad3forc3** [comment]
Great thanks. Any news on being able to use the older wine 1.50?

**Comment by ruanformigoni** [comment]
No problem. Still working on it, but facing some issues to make it work.

**Comment by Blad3forc3** [comment]
OK. Still testing this so if anything crops up i'll create a new issue. Thanks again
