### ISSUE TITLE
Wine version

### ISSUE THREAD

**Issue by LinuxToasty** [ruanformigoni/gameimage#19]
Excellent tool. Great work.

Quick query. When I am using I get an error saying that my wine version is out of date. 
It says that I am using 5.12 and is no longer supported.
Appimage builds correctly and works.
I am using Debian stable.

In winetricks I use dxvk 1.10.3 because the latest 2.0 versions do not work in stable and I get an error to say that it is incompatable with the wine version I am using.

The other feedback that may be useful is that before I get to the section "AppRun written, make further changes etc" the terminal outputs - "#Error echo "Could not start gameimage, remove $YAML and try again" I believe this is output for a script but initially I thought it was error when creating the appimage and may be confusing.

I may be talking nonsense and feel free to close if I am.

**Comment by ruanformigoni** [comment]
Hey there, thanks for the issue report! The version issue occurs in wine-ge, it does not seem to be a problem in gameimage. Is the message from the printing of the AppRun file in the terminal?

**Comment by Blad3forc3** [comment]
I have this too, the output is this after selecting the exe file to use:

#!/usr/bin/env bash

set -e

# Wine executable
DIR_CALL="$(dirname "$APPIMAGE")"
DIR_APP="$APPDIR"
WINE="$APPDIR/usr/bin/wine"

if [[ "$(basename "${APPIMAGE}")" =~ \.\.AppImage ]]; then
  # Set hidden config dir
  CFGDIR="$(dirname "$APPIMAGE")/$(basename "$APPIMAGE").config"
else
  # Set visible config dir
  CFGDIR="$(dirname "$APPIMAGE")/.$(basename "$APPIMAGE").config"
fi

# Remove invalid characters
CFGDIR="${CFGDIR//:/}"

# Path to appimage mountpoint
MNTDIR="$APPDIR"

# Export prefix
export WINEPREFIX="$CFGDIR/wine"

# Unmount after appimage unmounts squashfs
function _exit() { pkill -f "unionfs.*$WINEPREFIX"; }
trap _exit SIGINT EXIT

# Configure dirs for unionfs
export WINEPREFIX_RO="$MNTDIR/app/wine"
export WINEPREFIX_RW="$CFGDIR/union"
mkdir -p "$WINEPREFIX"
mkdir -p "$WINEPREFIX_RW"

# Mount prefix with unionfs
"$APPDIR/usr/bin/unionfs" -o uid="$(id -u)",gid="$(id -g)" -ocow "$WINEPREFIX_RW"=RW:"$WINEPREFIX_RO"=RO "$WINEPREFIX"

cd "$(dirname "$CFGDIR/wine/drive_c/game/blahblah.exe")"

EXEC="blahblah.exe"

# Avoid symlink creation
for i in "$WINEPREFIX/drive_c/users/$(whoami)/"{AppData,Application\ Data,Contacts,Desktop,Documents,Downloads,Favorites,Links,Music,My\ Documents,Pictures,Saved\ Games,Searches,Videos}; do
  # Erase symbolic link and replace with regular folder
  [ ! -L "$i" ] || rm "$i"
  [ -d "$i" ] || mkdir -p "$i"
done

YQ="$APPDIR/usr/bin/yq"

# Check YAML integrity
YAML="$CFGDIR/config.yml"
"$YQ" --exit-status 'tag == "!!map" or tag == "!!seq"' "$YAML" &>/dev/null || echo "cmd: \"{wine} {exec}\"" > "$YAML"

if [[ "$1" =~ --gameimage-cmd=(.*) ]]; then
  # Define custom Command
  YAML_CMD="${BASH_REMATCH[1]}"
  YAML_CMD="${YAML_CMD//\"/\\\"}" # Escape quotes
  "$YQ" -i ".cmd = \"$YAML_CMD\"" "$YAML"
elif { YAML_CMD="$("$YQ" '.cmd | select(.!=null)' "$YAML")"; [ -n "$YAML_CMD" ]; }; then
  # Run custom command, replaces {wine} and {exec} strings
  YAML_CMD="${YAML_CMD//\{wine\}/\"$WINE\"}"
  YAML_CMD="${YAML_CMD//\{exec\}/\"$EXEC\"}"
  YAML_CMD="${YAML_CMD//\{here\}/\"$DIR_CALL\"}"
  YAML_CMD="${YAML_CMD//\{appd\}/\"$DIR_APP\"}"
  eval "$YAML_CMD"
else
  # Error
  echo "Could not start gameimage, remove $YAML and try again"
fi
[*] AppRun written, make further changes to it if you desire, then press enter...

**Comment by ruanformigoni** [comment]
Thanks @Blad3forc3 ! I'll add some delimiters to show that this is the written file a not an error message.

**Comment by ruanformigoni** [comment]
Another pointer, if you download the [wine-ge](https://github.com/GloriousEggroll/wine-ge-custom/releases/tag/GE-Proton7-37) files, and run `./lutris-GE-Proton7-37-x86_64/bin/wine --version`, you'll get `wine-5.12-15683-g32b54e575c0 (Staging)`. Although dxvk says it does not support it, I seems to work fine.

**Comment by LinuxToasty** [comment]
All works fine with the warning. Strange. So the Wine version being used is the newer version?

**Comment by ruanformigoni** [comment]
Yes, I think that the displayed version is from when 'ge' was forked from vanilla wine.

**Comment by ruanformigoni** [comment]
Remaining issue with proper leading marker on the output of files resolved in latest version.
