### ISSUE TITLE
Wine-GE error

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#20]
When creating a new prefix within wine-ge an error occurs saying

[*] appimagetool: https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
appimagetool                                  100%[===============================================================================================>]   8.40M  6.99MB/s    in 1.2s    
[*] imagemagick: https://imagemagick.org/archive/binaries/magick
imagemagick                                   100%[===============================================================================================>]  26.32M  2.55MB/s    in 11s     
[*] Error fetching wine url
Terminated

**Comment by ruanformigoni** [comment]
Hi @Blad3forc3 , could this have been an internet connection issue? It seems to be working fine at the moment.

**Comment by Blad3forc3** [comment]
I export GIMG_WINE_DIST=wine-ge first? IS that th exact command for the GE version?

**Comment by ruanformigoni** [comment]
It is `GIMG_WINE_DIST=ge`, that is probably why it could not find it.

**Comment by Blad3forc3** [comment]
My bad Ruan. Close this :)

**Comment by ruanformigoni** [comment]
No problem, anything else I'm here :)
