### ISSUE TITLE
Old gameimage versions not available

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#21]
Can a version of older appimages be available to download? I'd like version 0.40 to test as i have a game that worked on that version but not on the latest version. I'd like to test this and with an older staging version

**Comment by ruanformigoni** [comment]
Hi @Blad3forc3! I don't plan to support older releases, [here is v.4.0.0](https://mega.nz/file/g15x1BCB#_pYQwSnbBuOxGrzS4zxzRbQhEpuneb4OPTzq4jpgrMY).

**Comment by Blad3forc3** [comment]
Thanks Ruan, would you have a copy wine staging 8.1 appimage too?

**Comment by ruanformigoni** [comment]
Hi @Blad3forc3 , sorry for the delay on getting back to you. I currently do not, however I'm working on the stable 8.0 version which should help.

**Comment by ruanformigoni** [comment]
I've been working in a replacement for appimage, which makes it easier to run applications in containers, you can check it out [here](https://gitlab.com/formigoni/arts). 

With this, you can build your own wine distribution really easily with:

./focal.arts
./focal.arts arts-resize 10G
./focal.arts arts-root dpkg --add-architecture i386
./focal.arts arts-root mkdir -pm755 /etc/apt/keyrings
./focal.arts arts-root apt install -y wget
./focal.arts arts-root wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
./focal.arts arts-root wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/focal/winehq-focal.sources
./focal.arts arts-root apt update
./focal.arts arts-root apt install --install-recommends winehq-staging

These instructions were taken from [here](https://wiki.winehq.org/Ubuntu).

**Comment by Blad3forc3** [comment]
Great Ruan. How do i inject an older wine build into this? I have wine 1.5.0 on my hard drive with the folders bin, lib and share inside it. Looking above this will always install the latest wine build, which is good but is it possible for me to use 1.5.0?

**Comment by ruanformigoni** [comment]
You can copy the binaries inside it and set it as the default command:

```sh
./focal.arts arts-root cp ./wine-1.5.0 /opt/
./focal.arts arts-cmd ./wine-1.5.0/bin/wine
mv focal.arts wine
./wine --version
```

**Comment by Blad3forc3** [comment]
I am failing on the first part. I have a folder called wine-1.5.0 next to focal.arts and when in type ./focal.arts arts-root cp ./wine-1.5.0 /opt i get this error 
cp: cannot stat './wine-1.5.0': No such file or directory

**Comment by ruanformigoni** [comment]
Weird, I managed to make wine-1.7.7 work, here:

![screenshot-148](https://user-images.githubusercontent.com/18180693/226117129-982540a3-aaae-4e40-b2fc-aa08993a9945.png)
