### ISSUE TITLE
Does not launch 

### ISSUE THREAD

**Issue by LinuxToasty** [ruanformigoni/gameimage#25]
Hi there,
Just downloaded the latest version and I am having an issue. 
I have tried to install a GOG game. First launch works fine.
Next launch I have-
fuse: mountpoint is not empty
fuse: if you are sure this is safe, use the 'nonempty' mount option
and doesn't launch.
I have tried to delete the hidden config file but I get "Error removing file: Device or resource busy" and it will not delete until reboot.
Old version works fine. I am on Linux Mint 21.1
Any ideas?

**Comment by ruanformigoni** [comment]
Hi, thanks for the feedback! That is probably because unionfs that failed to unmount, that might happen if the game or wine processes are still running. You can try `fusermount -u .my-game/wine`. Or `killall unionfs`. I'm not sure if this issue is exclusive to the new update.

**Comment by LinuxToasty** [comment]
Thanks for looking. I tried the old version and it had the same issue. 
It was my error!! I had save the game appimage in a folder with spaces.
As soon as I removed the spaces it worked!

Thanks for checking and sorry to raise issue.
