### ISSUE TITLE
Error fetching wine url

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#26]
I am getting the following error when creating an appimage from scratch

[*] AppDir from previous run found, remove it? [y/N]: 
[*] appimagetool: https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
[*] imagemagick: https://imagemagick.org/archive/binaries/magick
[*] Error fetching wine url

**Comment by ruanformigoni** [comment]
Hi @Blad3forc3 , just tested it and it worked for me. What wine distribution are you using?

**Comment by Blad3forc3** [comment]
I'm trying wine ge with
export GIMG_WINE_DIST=wine-ge

**Comment by ruanformigoni** [comment]
Oh it's `export GIMG_WINE_DIST=ge`.

**Comment by Blad3forc3** [comment]
Ok cool thanks but when i have an empty gameimage folder and i get to the option of downloading the wineprefix and select yes it doesnt download the wineprefix

**Comment by ruanformigoni** [comment]
Hi @Blad3forc3, thanks for the feedback! I've disabled this feature due to not working sometimes, as per the nvidia issue, it should be fixed in the latest wine-ge.
