### ISSUE TITLE
Nvidia json missing

### ISSUE THREAD

**Issue by LinuxToasty** [ruanformigoni/gameimage#27]
Hi there,
Currently have an issue when building-
Build/AppDir/app/wine/icd.d/nvidia_icd.i686.json: No such file or directory

I have Linux Mint 21.2 with Nvidia drivers from the repo installed.

Thanks

**Comment by ruanformigoni** [comment]
Hi @LinuxToasty, thanks for reporting this issue! I've updated wine-ge. Start with a fresh build directory to see if that has solved you issue.
