### ISSUE TITLE
Wrong Screen Orientation on the Steam Deck

### ISSUE THREAD

**Issue by mikhaelcool7** [ruanformigoni/gameimage#28]
Not only does the AppImage not start at all when launched through Steam as a Non-Steam game but once opened through the Desktop Mode, the game starts in the wrong screen orientation

**Comment by ruanformigoni** [comment]
Hi @mikhaelcool7 , thanks for reporting this issue. Could you provide details in what game you are trying to launch? Try to open steam through the terminal with `steam-runtime`, and checkout the log messages that appear when you try to launch the game. Could you try to use `gamescope` with the gameimage? That could potentially fix the orientation issue.

**Comment by mikhaelcool7** [comment]
> Hi @mikhaelcool7 , thanks for reporting this issue. Could you provide details in what game you are trying to launch? Try to open steam through the terminal with `steam-runtime`, and checkout the log messages that appear when you try to launch the game. Could you try to use `gamescope` with the gameimage? That could potentially fix the orientation issue.

I wrapped Diablo 2 + the LOD expansion and used the included Battle net updater in the game to get the game to the latest version. The entire process was done on a separate PC using Linux Mint Cinnamon 21.2. Works as intended on the separate PC. Wine Staging was used during the process too to get all the videos and fonts working. The exe target was set to Game.exe instead of Diablo II.exe as that is what fixed the game from not starting at all when wrapped

**Comment by ruanformigoni** [comment]
Hi @mikhaelcool7 , I'm closing this issue since `AppImage` is not supported by the project anymore, if the issue persists with the new format let me know.
