### ISSUE TITLE
Not an issue... more of a collaboration request to assist all...

### ISSUE THREAD

**Issue by Higherselfhiphop** [ruanformigoni/gameimage#30]
Hey y'all... I love all your up to...

New to AppImage... I've been collecting them all and making new ones... The latest being Mednafen... and  Mednaffe... For this is the next steps in transforming games into portable Linux packages... Efficiently... as in size matters and smaller AppImages are key... Thankfully my AppImages work and have got a few trials done... Yet need some assistance on getting Mednafen to load settings inside the Appimage or an AppImage that will copy the settings to the home directory before the rom launch...

Been working on a Chromebook distro... with coding and programming, not my thing... Yet with a little help, I wish to bring hundreds of legal games to the table in AppImage format and potentially start an AppImage Deb Repo, as combining the two is what Linux needs... So all the New apps and Games can be Unified into Synaptic and most importantly... Into the Gnone Software Center and K-Discover....

Looking forward to working and assisting, on bringing hundreds to thousands of "New" packages into an updated Repo....

First thing first... Getting Mednafen into the flow... As that brings over 300 "new" legal games to the platform...

Thanks again...
Bartman

**Comment by ruanformigoni** [comment]
Hey there, thanks for the willingness to help! Currently these are the projects I mostly work with:

* [Gameimage](https://gitlab.com/formigoni/gameimage)
* [Application Root Subsystem](https://gitlab.com/formigoni/arts) (Still a WIP)

If you wish to discuss something in detail, here is my email: `ruanformigoni@gmail.com`.
