### ISSUE TITLE
appimage was created but launching it does nothing

### ISSUE THREAD

**Issue by Blackfox-Thane** [ruanformigoni/gameimage#31]
So i tried to create an appimage for a emulator called 1964, it completed fine i start the image the GUI shows up, i select the option to launch the app but nothing happens then i try to start the app from the terminal this error shows

`sh: line 1: /home/thane/Gameimage/1964-Emulator/build/.1964.AppImage.config/wine/drive_c/Program Files (x86)/1964/1964.exe: Permission denied`

When i did this with Turok 2 and Dead Space it worked fine, but with this and some other games the error pops up.

OS: Artix Linux x86_64
Kernel: 6.5.2-artix1-1
CPU: AMD Ryzen 5 5600X (12) @ 3.700GHz
GPU: NVIDIA GeForce RTX 2070 SUPER

**Comment by ruanformigoni** [comment]
Hi @Blackfox-Thane , thank you for the issue report. I'll try to replicate this issue to see what's going on.

**Comment by Blackfox-Thane** [comment]
I managed to fix the problem to this, apparently i had to chmod the executable and now it runs smoothly, i'm still figuring out some other apps but thankfully this one issue is fixed
