### ISSUE TITLE
Does not work on immutable distros

### ISSUE THREAD

**Issue by CaptainMuskrat** [ruanformigoni/gameimage#33]
As a Fedora Silverblue user, I was excited with the prospect of preserving my Wine-dependent games as appimages, however upon trying to generate the file using the GUI, I get the following error

*] Yaml: /tmp/gameimage.yml
[*] Selected icon: /var/mnt/Samsung 990 Pro/Games/DungeonKeeper2/icon/cover.png
[*] build dir: /var/mnt/Samsung 990 Pro/Games/DungeonKeeper2/build
[*] appimagetool: https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
[*] imagemagick: https://imagemagick.org/archive/binaries/magick
Connecting to imagemagick.org (50.251.58.13:443)
wget: note: TLS certificate validation not implemented
wget: TLS error from peer (alert code 40): handshake failure
wget: error getting response: Connection reset by peer

It is just as well, because I tried using GameImage on other distributions in the past and it never worked either. The process would go through the motions, giving me the option to configure things along the way, and the game would run the first time just fine, but no Appimage was ever generated. I feel that more emphasis should be put on the GUI and out-of-the-box functionality, rather than inputting terminal commands or relying on third party dependencies not already present in the appimage.

**Comment by ruanformigoni** [comment]
Hi @CaptainMuskrat , thanks for the bug report! This specific issue seems like a connection error, could you try to click the build button again to see what happens? The AppImage is generated to the `build` folder, could you please post the terminal output for the process, so I can have more clues on why this is not happening? A GUI refactor is on my plans, in meantime I'll try to assist you with the currently available options.

**Comment by ruanformigoni** [comment]
Hi @CaptainMuskrat , I've updated the fetch tool to aria2, as well as the link to imagemagick. Furthermore, I'm moving away from appimage, to support flatimage instead, it is generated inside the `build` directory after the build phase.
