### ISSUE TITLE
Gameimage yaml tmp error on version 0.60

### ISSUE THREAD

**Issue by Blackfox-Thane** [ruanformigoni/gameimage#34]
Can't seen to get this version of gameimage to function correctly, every time i try to use the GUI to pack a rom I get this error

`*] Yaml: /tmp/gameimage.yml
Error: open /tmp/gameimage.yml: no such file or directory`

OS: Artix Linux x86_64
Kernel: 6.6.1-artix1-1
CPU: AMD Ryzen 5 5600X (12) @ 3.700GHz
GPU: NVIDIA GeForce RTX 2070 SUPER

**Comment by ruanformigoni** [comment]
Hi @Blackfox-Thane , thanks for reporting this issue. Could you try the newly released version v0.6.1 ? Thanks!

**Comment by Blackfox-Thane** [comment]
@ruanformigoni nice this version works TY for the quick fix and response

**Comment by ruanformigoni** [comment]
I'm glad that is worked! Feel free to re-open if the issue arises again.
