### ISSUE TITLE
Creating an appimage results in error

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#37]
This error occurs when selecting build and creating an appimage from the gui

[*] Invalid package type 'unionfs', valid values are 'flatimage,appimage'

**Comment by ruanformigoni** [comment]
Hi @Blad3forc3 , I'm going to close this assuming I solved your issue with the previous information about using `GIMG_PKG_METHOD` instead of `GIMG_PKG_TYPE`.
