### ISSUE TITLE
Critical Bug!

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#38]
When creating an appimage bash is spammed over a thousand times with this error 

bash: warning: shell level (1000) too high, resetting to 1

Bash is continually trying to open 1000 times

This results in freezing the computer forcing a reboot unless i close dolphin file manager

**Comment by Blad3forc3** [comment]
Any update on this Ruan? Ive had a look myself but whenever i run any gameimage bash just keeps loading
and get this error

continuebash: warning: shell level (1000) too high, resetting to 1

**Comment by ruanformigoni** [comment]
Thanks for the info, I'll only be able to get to this on sunday, we can chat on discord or something if you're available.

**Comment by Blad3forc3** [comment]
An update to this my AppDir must have got corrupt somehow and was calling a script within a script. That is sorted now as I had a backup AppDir. I'll post an update to creating a new AppDir and the error when trying to pull in wine staging during the setup in a short while

**Comment by ruanformigoni** [comment]
Note that you should not use appdirs from diferent versions of gameimage. Furthermore, the new default is flatimage, which does not support re-using appimage appdirs.

**Comment by Blad3forc3** [comment]
Thanks for that Ryan. The particular AppDirs were not from different
versions of game image. I will try and test the latest game image this
weekend

**Comment by Blad3forc3** [comment]
Ok ive tested it and it is indeed ok. I have opened a new bug with an idea

**Comment by ruanformigoni** [comment]
Closing this, thanks for confirming it was an version issue.
