### ISSUE TITLE
When creating the flatimage can there be a progress status?

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#39]
Having just created a flatimage can there be a status indicator when creating the appimage
mksquashfs used to provide a status indicator...%
Edit to this.
When creating a new flatimage after i have selected the wine versions (staging in my case) and whether i want dxvk installed or not, on the next screen  i select build and i get this error:

Invalid package type 'overlayfs', valid values are 'flatimage,appimage'

**Comment by ruanformigoni** [comment]
Hi @Blad3forc3 , what environment variables a you setting? `GIMG_PKG_TYPE` is now used in the latest version for the type of packaging (flatimage or appimage), the environment variable to select overlayfs is `GIMG_PKG_METHOD`, as `export GIMG_PKG_METHOD=overlayfs`, but this is the default now. If you are not manually setting any environment variable, let me know.

**Comment by Blad3forc3** [comment]
Ok Ive created a new folder from scratch. Sorry i didnt realise there was a different PKG TYPE or PKG METHOD. I have now set these but when creating a new flatimage i get this error when fetching wine

Could not fetch wine url for 'staging', valid values are 'ge,caffe,vaniglia,soda'

Is staging not existing anymore?

**Comment by ruanformigoni** [comment]
No yet, use vaniglia instead.

**Comment by Blad3forc3** [comment]
ok now hen i select the option to install i get this

ln: failed to create symbolic link '/media/ade/Temp/Staging64a/build/AppDir/app/wine/dosdevices/z:': No such file or directory

**Comment by ruanformigoni** [comment]
I'm trying to replicate in an external hard drive, I think it might be an issue related to running outside your home directory.

**Comment by Blad3forc3** [comment]
Ok I don't run it from my home folder due to smaller free space

**Comment by ruanformigoni** [comment]
[Here](https://mega.nz/file/EkhTSYLb#pPqnEFFQOCZEziI-aeAli4pQ6gmxEpCNU-YYGkNFdZ8) is a patched build, let me know if that solves the issue. It only happens with Nvidia GPUs.

**Comment by Blad3forc3** [comment]
Thanks Ruan. I do indeed get to build a flatimage now.

I have a few observations to add

1..I have to type export GIMG_PKG_TYPE=flatimage before using the gui otherwise it fails telling me the error previously
Invalid package type 'overlayfs', valid values are 'flatimage,appimage'
Wouldnt it be better to have an option in the gui to eliminate this?
2..The terminal window...It would be much more convenient for the cursor to be on the input commands for the terminal because at the moment the mouse loses focus on the output window and I have to continually click the send command window to input an option
3..When I create a flatimage the resulting flatimage doesnt have the icon i put into the icon folder just a generic icon
4..The biggest one, when i double click the flatimage just created it fails with this error

execvp: Text file busy

**Comment by ruanformigoni** [comment]
I'm glad it worked! I'll investigate the pointers, for the third one, I have not yet implemented icons for flatimage. Does the fourth one only happens when running from a file manager? I'll create issues to look into the other problems, thanks for helping out! Flatimage is a necessary change to achieve the distro portability this project aims for, and also solve issues like #36

**Comment by Blad3forc3** [comment]
The fourth one does indeed happen when i run the gameimage from dolphin file manager.
It did work but the game i was trying just refuses to run. When i tried it on the old appimage it did at least get to the title screen before freezing

**Comment by ruanformigoni** [comment]
About the progress indicator, it seems to show the progress for me on the GUI:
![Screenshot_20231218_090310](https://github.com/ruanformigoni/gameimage/assets/18180693/9aa32d3b-3e47-48e9-8196-9554cfc294c3)
Is this not showing up for you, or do you have something else in mind?

**Comment by Blad3forc3** [comment]
Ah yes it is. I was thinking more of the old way progressing from left to right

**Comment by ruanformigoni** [comment]
This is the way that dwarfs outputs progress by default, I can suppress some information with --log-level=error, but the progress is still in a per-line style. Also, I've re-introduced wine staging, and other new distributions for flatimage.

**Comment by ruanformigoni** [comment]
Just an update, GIMG_PKG_METHOD now works on the GUI again.

**Comment by ruanformigoni** [comment]
> 4..The biggest one, when i double click the flatimage just created it fails with this error

This is now fixed, it was a problem with the output streams and the handling of resizing the container.

**Comment by ruanformigoni** [comment]
> 3..When I create a flatimage the resulting flatimage doesnt have the icon i put into the icon folder just a generic icon

Icon integration completed, you should see it after the first execution of the image. I'll leave the progress status as is for now, it is better to debug potential issues.
