### ISSUE TITLE
Fetching Option bug?

### ISSUE THREAD

**Issue by Blackfox-Thane** [ruanformigoni/gameimage#40]
Hello. So i have an problem with the Gameimage's fetching option, it's been stuck at "Download imagemagick: https://imagemagick.org/archive/binaries/magick" for 3 hours now and still haven't completed yet. Any advice?

**Comment by ruanformigoni** [comment]
Hi @Blackfox-Thane , that could be a connection error. I've tried it here and it seems to be working from my side.

**Comment by ruanformigoni** [comment]
I've updated the link to imagemagick, which uses a faster download source from github, that should do it.
