### ISSUE TITLE
Latest flatimage refuses to run

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#41]
I get nothing when double clicking the run file (set as excutable)
This is what i get from the terminal

Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing Gameimage  100%  
[*] Package type: flatimage
XOpenIM() failed
/tmp/selfgz11045/bin/wizard.sh: line 13: 11206 Arithmetic exception    (core dumped) LD_PRELOAD="$PATH_SCRIPT/preload-sandbox.so" "$PATH_SCRIPT/wizard"

**Comment by ruanformigoni** [comment]
Hi @Blad3forc3 , thanks for reporting this issue. I've encountered it before, it is not on flatimage, but on the gameimage package. I've sent a fix on `v0.6.9`, is this the version you are using?

**Comment by Blad3forc3** [comment]
Yes version 0.6.9 gives me this error

Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing Gameimage  100%  
[*] Package type: flatimage
XOpenIM() failed
/tmp/selfgz6327/bin/wizard.sh: line 13:  6490 Arithmetic exception    (core dumped) LD_PRELOAD="$PATH_SCRIPT/preload-sandbox.so" "$PATH_SCRIPT/wizard"

Also on your latest flatimage when i type ./jammy.fim i get this error

bash: ./jammy.fim: Text file busy

**Comment by ruanformigoni** [comment]
Could you tell me what is the output of `ls -Rla /tmp/gameimage/`, after trying to run the `.run` file?

**Comment by Blad3forc3** [comment]
Not a problem Ruan, this is the output after trying to run the gameimage run file

ls -Rla /tmp/gameimage/
/tmp/gameimage/:
total 52
drwx------  5 ade  ade   4096 Dec 27 14:17 .
drwxrwxrwt 23 root root 28672 Dec 27 14:36 ..
drwx------  2 ade  ade   4096 Dec 27 14:17 bin
-rw-------  1 ade  ade   2060 Dec 27 14:36 gameimage.png
drwx------  2 ade  ade   4096 Dec 27 14:17 preloader
drwx------  3 ade  ade   4096 Dec 27 14:17 share

/tmp/gameimage/bin:
total 2108
drwx------ 2 ade ade    4096 Dec 27 14:17 .
drwx------ 5 ade ade    4096 Dec 27 14:17 ..
-rwx------ 1 ade ade 2149648 Dec 27 14:36 bash

/tmp/gameimage/preloader:
total 644
drwx------ 2 ade ade   4096 Dec 27 14:17 .
drwx------ 5 ade ade   4096 Dec 27 14:17 ..
-rwx------ 1 ade ade 649832 Dec 27 14:36 ld-musl-x86_64.so.1

/tmp/gameimage/share:
total 12
drwx------ 3 ade ade 4096 Dec 27 14:17 .
drwx------ 5 ade ade 4096 Dec 27 14:17 ..
drwx------ 3 ade ade 4096 Dec 27 14:17 fonts

/tmp/gameimage/share/fonts:
total 12
drwx------ 3 ade ade 4096 Dec 27 14:17 .
drwx------ 3 ade ade 4096 Dec 27 14:17 ..
drwx------ 2 ade ade 4096 Dec 27 14:17 noto

/tmp/gameimage/share/fonts/noto:
total 12868
drwx------ 2 ade ade   4096 Dec 27 14:17 .
drwx------ 3 ade ade   4096 Dec 27 14:17 ..
-rw------- 1 ade ade 632668 Dec 27 14:36 NotoSans-BoldItalic.ttf
-rw------- 1 ade ade 610400 Dec 27 14:36 NotoSans-Bold.ttf
-rw------- 1 ade ade 624680 Dec 27 14:36 NotoSans-Italic.ttf
-rw------- 1 ade ade 966008 Dec 27 14:36 NotoSansMath-Regular.ttf
-rw------- 1 ade ade 606704 Dec 27 14:36 NotoSansMono-Bold.ttf
-rw------- 1 ade ade 592188 Dec 27 14:36 NotoSansMono-Regular.ttf
-rw------- 1 ade ade 603936 Dec 27 14:36 NotoSans-Regular.ttf
-rw------- 1 ade ade 666244 Dec 27 14:36 NotoSansSymbols2-Regular.ttf
-rw------- 1 ade ade 235968 Dec 27 14:36 NotoSansSymbols-Black.ttf
-rw------- 1 ade ade 228028 Dec 27 14:36 NotoSansSymbols-Bold.ttf
-rw------- 1 ade ade 229908 Dec 27 14:36 NotoSansSymbols-ExtraBold.ttf
-rw------- 1 ade ade 232496 Dec 27 14:36 NotoSansSymbols-ExtraLight.ttf
-rw------- 1 ade ade 228800 Dec 27 14:36 NotoSansSymbols-Light.ttf
-rw------- 1 ade ade 227616 Dec 27 14:36 NotoSansSymbols-Medium.ttf
-rw------- 1 ade ade 226980 Dec 27 14:36 NotoSansSymbols-Regular.ttf
-rw------- 1 ade ade 228356 Dec 27 14:36 NotoSansSymbols-SemiBold.ttf
-rw------- 1 ade ade 231428 Dec 27 14:36 NotoSansSymbols-Thin.ttf
-rw------- 1 ade ade 777288 Dec 27 14:36 NotoSerif-BoldItalic.ttf
-rw------- 1 ade ade 769364 Dec 27 14:36 NotoSerif-Bold.ttf
-rw------- 1 ade ade 682972 Dec 27 14:36 NotoSerifDisplay-BoldItalic.ttf
-rw------- 1 ade ade 682480 Dec 27 14:36 NotoSerifDisplay-Bold.ttf
-rw------- 1 ade ade 676588 Dec 27 14:36 NotoSerifDisplay-Italic.ttf
-rw------- 1 ade ade 670076 Dec 27 14:36 NotoSerifDisplay-Regular.ttf
-rw------- 1 ade ade 752236 Dec 27 14:36 NotoSerif-Italic.ttf
-rw------- 1 ade ade 738828 Dec 27 14:36 NotoSerif-Regular.ttf

**Comment by ruanformigoni** [comment]
Thanks for that, I'll investigate on a new kubuntu machine. For the `bash: ./jammy.fim: Text file busy`, this can happen when the application is still open (or it has hung or in a crashed state). If you run the mount command, you should see some line like this one: `/home/ruan/Downloads/jammy.fim on /tmp/fim/instance/4f25483_20231224135601/mount/ENmLoc type fuse.ext4)`. If your application is not running anymore, you can use something like `fusermount -u /tmp/fim/instance/4f25483_20231224135601/mount/ENmLoc` to fix this. Otherwise, try to kill it in the process manager beforehand. This is indeed a point of improvement, I get this error with AppImage too sometimes, I think that a tray icon to indicate that the application is running, with a 'kill' option on right click could help.

**Comment by ruanformigoni** [comment]
I was able to replicate the issue. Sorry for these recent bumps, I'm trying to reach the end goal of this project, to be runnable in several linux distros without additional dependencies, the recent changes and move to flatimage already allows it to run on alpine linux, also it does not require the fuse library installed on the host unlike it was with appimage. Thanks for your help to identify these problems :smile:

**Comment by Blad3forc3** [comment]
It's no problem Ruan. I will try and use the flatimage when it is more usable of course :)
One question once flatimage is better would it be relatively simple to convert an older appimage into a flatimage because i have made a few (over 1500) :)

**Comment by ruanformigoni** [comment]
It should be working now on `v0.7.0`. That's a lotta games :smile: Yes, that could be achieved with a simple script.

**Comment by Blad3forc3** [comment]
WHen i run 0.7.0 and select build, after ive slected the exe i get this

[*] Install method: overlayfs
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

**Comment by ruanformigoni** [comment]
That's odd, maybe it is a missing file or corrupt build dir, it worked on a kubuntu 23.10 VM.

**Comment by ruanformigoni** [comment]
Should be fixed by the project rework :smile:
