### ISSUE TITLE
Error: /tmp/aria2c-stdout: No such file or directory

### ISSUE THREAD

**Issue by ak-42** [ruanformigoni/gameimage#42]
Hi. I just found your project, and it looks super cool. I've been hoping for something like this since I found the abandoned project called [winepak](https://github.com/winepak/winepak).

However, I'm hitting the following error.

```
user@machine:~/Games/GameImage$ ./GameImage-x86_64.AppImage --platform=yuzu --name="game" --dir=./game-dir
[*] Package type: flatimage
[*] Selected rom: /home/user/Games/GameImage/build/game-dir/rom/game.nsp
[*] Selected icon: /home/user/Games/GameImage/build/game-dir/icon/cover.png
[*] Selected bios: /home/user/Games/GameImage/build/game-dir/bios/Firmware 17.0.1.zip
[*] Selected keys: /home/user/Games/GameImage/build/game-dir/keys/Keys 17.0.0.7z
[*] build dir: /home/user/Games/GameImage/build/game-dir/build
[*] AppDir from previous run found, remove it? [y/N]: 
[*] Fetch https://api.github.com/repos/flatimage/flatimage-yuzu/releases/latest
cat: /tmp/aria2c-stdout: No such file or directory
[*] yuzu: 
[*] Download ./AppDir/usr/bin/yuzu: 
```
At this point, the program just exits. Same error happen when uisng the GUI.
I do have `aria2c` installed, and the -v flag output `aria2 version 1.36.0`.

Am I missing something obvious or is this a bug?

---
Also, entirely unrelated to this bug/issue, but is there any way to use Yuzu-EA? Maybe an .AppImage from https://github.com/pineappleEA/pineapple-src?

**Comment by ruanformigoni** [comment]
Hi @ak-42 , thanks for reporting this issue! GameImage uses its own aria2c binary, so there is no need to install it on your machine, from what I've tested this issue happens when there is no internet connection. Try to verify if you can access the mentioned link `https://api.github.com/repos/flatimage/flatimage-yuzu/releases/latest` through your browser. Yes it is possible to use yuzu EA, I'll include it as a configuration option in the next release :smile:

**Comment by ak-42** [comment]
Yes, I can access the URL. I get structured JSON, which I imagine is what is expected. I even tried downloading the `yuzu-arch.fim` manually and putting it in the `/bin/` folder referenced above, but it didn't recognise it.

Excellent news on Yuzu EA, thank you.

**Comment by ruanformigoni** [comment]
Ah, this instructions are out of date, I'll update them. I switched from AppImage to [makeself](https://github.com/megastep/makeself). Sorry about the confusion, and I'm glad it works.

**Comment by ruanformigoni** [comment]
To configure the emulator inside the flatimage you can use the config flag: `my-game.flatimage --config`. Just to confirm, is the command you're using on the cli something like this? `~/Downloads/gameimage.run --platform=yuzu --name=my_game --dir=/path/to/my/game`. You can try to remove the temporary files directory to see if that is causing this problem with `rm -rf /tmp/gameimage`. What is you distro? I'll try to replicate on it if possible.

**Comment by ak-42** [comment]
I get this

```
user@machine:~/Games/GameImage$ ./gameimage.run --platform=yuzu --name="The Game" --dir=./game-dir
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing Gameimage  100%  
[*] Package type: flatimage
[*] Invalid src dir /tmp/selfgz1170634080/game-dir
Terminated
```
I did remove `/tmp/gamimage`, it did not help. I can see that the directory `selfgz1170634080` is created, but it is deleted the moment the program terminates.
I'm running Nobara 39 (which is basically Fedora 39).

I'm happy to help you debug this? Can I perhaps turn on debug level logging or something?

**Comment by ruanformigoni** [comment]
Sorry for the delay in getting back to you on this. If you use the absolute path it should work, e.g.:  `-dir="$(pwd)/game-dir"`. I'll test the config issue, probably has to do with an early exit or something.
