### ISSUE TITLE
why use FLTK GUI library?

### ISSUE THREAD

**Issue by Heus-Sueh** [ruanformigoni/gameimage#46]
I ask this because the interface is not very pleasing to the eye because it is old, but I understand that one of the reasons was because it is light, but I think the project would benefit from a more modern GUI and since you rewrote a lot of the code in C++ maybe this would be the right time to change, maybe QT which is made in C++, GTK or [Iced](https://iced.rs/) if you still intend to leave the GUI in Rust

Since you prefer C++, I think it would be better to keep the code in just one language to attract more contributions

**Comment by Blad3forc3** [comment]
I'm not sure if this is related but i'm using kubuntu with an nivdia card and when i am running gameimage the mouse becomes stuttery definitely not smooth as soon as i close gameimage the mouse is fine. Also any chance the logger windows can use larger fonts? They look tiny and also jaggy

**Comment by ruanformigoni** [comment]
Wayland support is now enabled for fltk-rs, with should mitigate issues that were present in  Xwayland. Now scaling (wayland) is working properly on both launcher and wizard.
