### ISSUE TITLE
[Feature Request] Add an option to select different Wine-GE versions while building the flatimage

### ISSUE THREAD

**Issue by casasfernando** [ruanformigoni/gameimage#47]
Not sure if this is possible for gameimage (it seems you are building your own Wine-GE instead of fetching the ones from https://github.com/GloriousEggroll/wine-ge-custom), but similarly to the Wine Manager feature in Heroic launcher, it would be great to be able to choose different Wine-GE versions to use (and embed in the image) while building the flatimage.

Today I was building one flatimage and found that the application I wanted to package is not working fullscreen with the latest versions of Wine-GE but after trying to make the same application work in Heroic launcher, I found that Wine-GE-Proton8-8 was the last version were the application was working fullscreen correctly. So there I can simply select that version of Wine-GE to run that specific application, while I can use the latest one for the rest.

Thanks

**Comment by ruanformigoni** [comment]
Hi @casasfernando , thanks for the suggestion!

I do not build my own, and do fetch from `https://github.com/GloriousEggroll/wine-ge-custom`, you can see the whole process [here](https://github.com/gameimage/runners). This seems like the same issue as #4 , it is possible but I cannot give an estimate on how long that will take. I'll keep this open and close when it is implemented :smile:

**Comment by casasfernando** [comment]
Thanks for considering this.

**Comment by ruanformigoni** [comment]
Feature implemented, you can use any wine version you want by providing the tarball, with the `wine_custom` option:

![wine-custom](https://github.com/ruanformigoni/gameimage/assets/18180693/a316b0a5-6bb7-44c9-8f63-b73c7b7b7dad)

**Comment by casasfernando** [comment]
Thanks!
