### ISSUE TITLE
Error when fetching required files

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#48]
I am getting these errors when fetching staging.dwarfs and base.flatimage.tar.xz

SHA check failed for '"/media/ade/Temp/Temp/build/wine.dwarfs"'
Download result: Err(Download failed for /media/ade/Temp/Temp/build/wine.dwarfs.sha256sum: (verification: unverified):
  1: https://github.com/gameimage/runners/releases/download/wine-gnu-x86_64/staging.dwarfs.sha256sum with status 400
  2: https://github.com/gameimage/runners/releases/download/wine-gnu-x86_64/staging.dwarfs.sha256sum with status 400
  3: https://github.com/gameimage/runners/releases/download/wine-gnu-x86_64/staging.dwarfs.sha256sum with status 400
)
SHA check failed for '"/media/ade/Temp/Temp/build/wine.tar.xz"'
Download result: Err(Download failed for /media/ade/Temp/Temp/build/wine.tar.xz.sha256sum: (verification: unverified):
  1: https://github.com/gameimage/runners/releases/download/wine-gnu-x86_64/base.flatimage.tar.xz.sha256sum with status 400
  2: https://github.com/gameimage/runners/releases/download/wine-gnu-x86_64/base.flatimage.tar.xz.sha256sum with status 400
  3: https://github.com/gameimage/runners/releases/download/wine-gnu-x86_64/base.flatimage.tar.xz.sha256sum with status 400
)

**Comment by ruanformigoni** [comment]
Hi @Blad3forc3 , thanks for the issue report! Does this error happen right away or after some time downloading?

**Comment by Blad3forc3** [comment]
First time i've run the release. Just opened it selected a temp dir then wine and what version of when then the next screen says fetch those two files then it errors

**Comment by ruanformigoni** [comment]
Tested on arch, fedora and ubuntu. Seems to only happen on ubuntu.

**Comment by ruanformigoni** [comment]
Should be fixed now on v1.0.1

**Comment by Blad3forc3** [comment]
It is fixed thanks
