### ISSUE TITLE
Unexpected EOF while looking for matching `"'

### ISSUE THREAD

**Issue by tanner02** [ruanformigoni/gameimage#5]
Throws an error after it downloaded the needed files.

> (deck@steamdeck stuff)$ /home/deck/Downloads/GameImage.AppImage --platform=wine --name="Need for Speed: ProStreet" --dir=/run/media/mmcblk0p1/Games/ProStreet
> [\*] Selected icon: /run/media/mmcblk0p1/Games/ProStreet/icon/cover.png
> [\*] build dir: /run/media/mmcblk0p1/Games/ProStreet/build
> [\*] appimagetool: https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
> appimagetool                       100%[==============================================================>]   8.40M  11.2MB/s    in 0.8s    
> [\*] imagemagick: https://imagemagick.org/archive/binaries/magick
> imagemagick                        100%[==============================================================>]  27.18M  2.21MB/s    in 13s     
> [\*] wine: https://github.com/ruanformigoni/wine/releases/download/continuous-ge/wine-ge-7-35-continuous-x86_64.AppImage
> /tmp/.mount_Gam6kb3Qk/usr/bin/common.sh: eval: line 32: unexpected EOF while looking for matching `"'

SteamOS 3.4.4

**Comment by ruanformigoni** [comment]
Hi @tanner02 , thanks for the heads up! This is now fixed in version `0.3.4`.

**Comment by tanner02** [comment]
Hi @ruanformigoni, you're welcome and thank you for the quick fix! I will now close the issue.
