### ISSUE TITLE
Issue selecting icon

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#51]
When i select a png icon i get an error the icon isnt in png format

Log error

Installing icon...
I :: Open file '"/media/ade/Temp/Temp/build/gameimage.json"' as READ
I :: Open file '"/media/ade/Temp/Temp/build/gameimage.json"' as READ
I :: Open file '"/media/ade/Temp/Temp/build/gameimage.json"' as READ
I :: Open file '"/media/ade/Temp/Temp/build/gameimage.json"' as READ
I :: Reading image from "/media/ade/Temp/ageofempires.png"
I :: Usage: install [--help] [--version] [--remove] [--remote] args
I :: 
I :: Install a file to the current project
I :: 
I :: Positional arguments:
I ::   args           Install an application into the default directory [nargs: 0 or more] [required]
I :: 
I :: Optional arguments:
I ::   -h, --help     shows help message and exits 
I ::   -v, --version  prints version information and exits 
I ::   --remove       Removes an installed file/dir 
I ::   --remote       Install core from remote 
I :: Image types aren't compatible.: iostream error
Could not install icon, use .jpg or .png

**Comment by ruanformigoni** [comment]
Hi @Blad3forc3 , I get these issues with fake `png` files sometimes, can you try to do `convert my-image.png my-new-image.png` to see if that makes it work? The convert command is part of the imagemagick suite, you can also use gimp or other software to export the imported image as a new png.

**Comment by Blad3forc3** [comment]
Ok attached the zip file
[ageofempires.zip](https://github.com/ruanformigoni/gameimage/files/14853494/ageofempires.zip)

**Comment by ruanformigoni** [comment]
@Blad3forc3 thanks a lot for the help on this. It should be fixed on patch 1.0.2. I have also fixed the alpha channel missing on the input png images, some tips:

If you want the result to be something like this:

![launcher-ageofempires](https://github.com/ruanformigoni/gameimage/assets/18180693/2c87b9c9-2b18-4be5-8db3-8b9895149b20)

On gimp, go to image -> resize canvas. Set the canvas size to 600x900 and click on center.

![preserved-aspect-ratio](https://github.com/ruanformigoni/gameimage/assets/18180693/ed57cf9d-a38f-471a-b0b3-c77c8f8ae3d5)

On the desktop icon selection screen, select the original icon.

**Comment by Blad3forc3** [comment]
Ok thanks Ruan that seems to have worked. You can close this
