### ISSUE TITLE
Error When configuring wine

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#54]
When you get to the stage of selecting configure wine in the flatimage (Install dxvk etc) if you dont want to configure anything and just select next i get this error

Reading as 'png'
I :: Image size is 600x900
I :: Image  aspect ratio is 0.666667
I :: Target aspect ratio is 0.666667
I :: Resizing image to 600x900
I :: Writing image to "/media/ade/Temp/Temp/build/Star-Wars-Empire-At-War/icon/icon.png"
I :: Writing grayscale image to "/media/ade/Temp/Temp/build/Star-Wars-Empire-At-War/icon/icon.grayscale.png"
I :: Open file '"/media/ade/Temp/Temp/build/gameimage.json"' as READ
I :: Open file '"/media/ade/Temp/Temp/build/Star-Wars-Empire-At-War/gameimage.json"' as UPDATE
Wine prefix does not exist

only if i select an option does it create the wineprefix

So if select nothing and select next straight awy i get the winprefix doesnt exist error but if i select any option, to run a wine custom command for example does it create the wineprefix and only after this can i click next

**Comment by ruanformigoni** [comment]
Hi @Blad3forc3 , currently it is required to perform an action to create the prefix before continuing. You can open for regedit and close to satisfy this. I did not yet find a suitable way to 'create wine prefix if not exists and do nothing' solution.

**Comment by Blad3forc3** [comment]
OK not a problem, it just stood out and thought id report it

**Comment by ruanformigoni** [comment]
No problem, don't hesitate in reporting things that you find bothersome. I'll leave this open while this is not implemented, so you get notified when it is.

**Comment by ruanformigoni** [comment]
Fixed, now the prefix is created without any explicit configuration :smile:
