### ISSUE TITLE
Random loss of usb keyboard and mouse during install

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#56]
When running gameimage and getting to the install application, in my case a gog game installer my system loses both the usb mouse and keyboard input

The log file is as follows:

I :: [o] :: [wine.sh] Switched directory to: /media/ade/Temp/Star.Wars.Empire.at.War.Gold.Pack-GOG
I :: [e] :: [wine.sh]   Major opcode of failed request:  131 (XInputExtension)
I :: [e] :: [wine.sh]   Minor opcode of failed request:  3 (X_OpenDevice)
I :: [e] :: [wine.sh]   Device id in failed request: 0x5600003
I :: [e] :: [wine.sh]   Serial number of failed request:  87
I :: [e] :: [wine.sh]   Current serial number in output stream:  87
I :: [e] :: [wine.sh] X Error of failed request:  XI_BadDevice (invalid Device parameter)
I :: [e] :: [wine.sh]   Major opcode of failed request:  131 (XInputExtension)
I :: [e] :: [wine.sh]   Minor opcode of failed request:  3 (X_OpenDevice)
I :: [e] :: [wine.sh]   Device id in failed request: 0x169
I :: [e] :: [wine.sh]   Serial number of failed request:  567
I :: [e] :: [wine.sh]   Current serial number in output stream:  567
I :: Finished Command: '/media/ade/Temp/Temp/build/wine.flatimage fim-exec wine.sh /media/ade/Temp/Star.Wars.Empire.at.War.Gold.Pack-GOG/setup_sw_empire_at_war_gold_2.0.0.3.exe'
I :: Open file '"/media/ade/Temp/Temp/build/gameimage.json"' as READ

i cannot continue unless i unplug both devices and plug in again

**Comment by ruanformigoni** [comment]
Thanks for the report! I think I remember you having this issue before, this is a bit harder to reproduce from my side. Could you leave this info as reference, so I could dig a little deeper?

Session type: Execute `echo $XDG_SESSION_TYPE`
Linux release info: Run `cat /etc/*-release`
GPU info: Run `glxinfo -B`

Btw, I think that switching to a wayland session would serve as a workaround while this is not fixed.

**Comment by Blad3forc3** [comment]
Just an update to this, here is the log file where the error occurs

I :: prefix: "/media/ade/Temp/Temp/build/Age-Of-Empires-Rise-Of-Rome/wine"
I :: [o] :: [wine.sh] Container   : arch
I :: [e] :: [wine.sh] X Error of failed request:  XI_BadDevice (invalid Device parameter)
I :: [o] :: [wine.sh] Session Type: x11
I :: [o] :: [wine.sh] $*          : /media/ade/Temp/Age_of_Empires_Repack_v3/Age of Empires_Repack_v3_Setup.exe
I :: [o] :: [wine.sh] HOME        : /media/ade/Temp/Temp/build
I :: [o] :: [wine.sh] WINEPREFIX  : /media/ade/Temp/Temp/build/Age-Of-Empires-Rise-Of-Rome/wine
I :: [o] :: [wine.sh] WINEHOME    : /wine/home
I :: [o] :: [wine.sh] glxinfo log : /media/ade/Temp/Temp/build/Age-Of-Empires-Rise-Of-Rome/wine/glxinfo.log
I :: [o] :: [wine.sh] GPU Vendor  : nvidia corporation
I :: [o] :: [wine.sh] GPU Device  : NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
I :: [o] :: [wine.sh] OpenGL      : 4.6.0 NVIDIA 550.54.14
I :: [o] :: [wine.sh] Vulkan log  : /media/ade/Temp/Temp/build/Age-Of-Empires-Rise-Of-Rome/wine/vulkan.log
I :: [o] :: [wine.sh] /fim/mount/wine/bin/wine
I :: [o] :: [wine.sh] Wine version: wine-9.5 (Staging)
I :: [o] :: [wine.sh] Switched directory to: /media/ade/Temp/Age_of_Empires_Repack_v3
I :: [e] :: [wine.sh]   Major opcode of failed request:  131 (XInputExtension)
I :: [e] :: [wine.sh]   Minor opcode of failed request:  3 (X_OpenDevice)
I :: [e] :: [wine.sh]   Device id in failed request: 0x6e00003
I :: [e] :: [wine.sh]   Serial number of failed request:  87
I :: [e] :: [wine.sh]   Current serial number in output stream:  87
I :: [e] :: [wine.sh] X Error of failed request:  XI_BadDevice (invalid Device parameter)
I :: [e] :: [wine.sh]   Major opcode of failed request:  131 (XInputExtension)
I :: [e] :: [wine.sh]   Minor opcode of failed request:  3 (X_OpenDevice)
I :: [e] :: [wine.sh]   Device id in failed request: 0x1d7
I :: [e] :: [wine.sh]   Serial number of failed request:  612
I :: [e] :: [wine.sh]   Current serial number in output stream:  612
I :: Finished Command: '/media/ade/Temp/Temp/build/wine.flatimage fim-exec wine.sh /media/ade/Temp/Age_of_Empires_Repack_v3/Age of Empires_Repack_v3_Setup.exe'

It happened when i was testing the application

**Comment by Blad3forc3** [comment]
Another USB crash

I :: [o] :: [wine.sh] Container   : arch
I :: [e] :: [wine.sh] wineserver: using server-side synchronization.
I :: [o] :: [wine.sh] Session Type: x11
I :: [o] :: [wine.sh] $*          : regedit
I :: [o] :: [wine.sh] HOME        : /media/ade/Temp/Temp/build
I :: [o] :: [wine.sh] WINEPREFIX  : /media/ade/Temp/Temp/build/Age-Of-Empires/wine
I :: [o] :: [wine.sh] WINEHOME    : /wine/home
I :: [o] :: [wine.sh] glxinfo log : /media/ade/Temp/Temp/build/Age-Of-Empires/wine/glxinfo.log
I :: [o] :: [wine.sh] GPU Vendor  : nvidia corporation
I :: [o] :: [wine.sh] GPU Device  : NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
I :: [o] :: [wine.sh] OpenGL      : 4.6.0 NVIDIA 550.54.14
I :: [o] :: [wine.sh] Vulkan log  : /media/ade/Temp/Temp/build/Age-Of-Empires/wine/vulkan.log
I :: [o] :: [wine.sh] /fim/mount/wine/bin/wine
I :: [o] :: [wine.sh] Wine version: wine-8.0-3001-g39021e609a2 (Staging)
I :: [e] :: [wine.sh] wine: Using setpriority to control niceness in the [-19,19] range
I :: [e] :: [wine.sh] 0088:err:hid:udev_bus_init UDEV monitor creation failed
I :: [e] :: [wine.sh] 0034:err:service:process_send_command receiving command result timed out
I :: Finished Command: '/media/ade/Temp/Temp/build/wine.flatimage fim-exec wine.sh regedit'

**Comment by Blad3forc3** [comment]
Another little update to this, I have made 4 or 5 flatpacks today and every time i have had to replug my USB keyboard and mouse at least 2 time during the flatimage creation

X Error of failed request:  XI_BadDevice (invalid Device parameter)
I :: [e] :: [wine.sh]   Major opcode of failed request:  131Major opcode of failed request:  131 (XInputExtension)
I :: [e] :: [wine.sh]  (XInputExtension)
I :: [e] :: [wine.sh]   Minor opcode of failed request:  3  Minor opcode of failed request:  3 (X_OpenDevice)
I :: [e] :: [wine.sh]  (X_OpenDevice)
I :: [e] :: [wine.sh]   Device id in failed request: 0x1d7  
I :: [e] :: [wine.sh] Device id in failed request: 0x6800003  
I :: [e] :: [wine.sh] Serial number of failed request:  560  
I :: [e] :: [wine.sh]   Serial number of failed request:  87Current serial number in output stream:  560

**Comment by Blad3forc3** [comment]
Gameimage does run smoothly in wayland (no USB dropouts) with the obvious problem that you cant preview the file running as wine hasnt implemented wayland protocols yet?

**Comment by Blad3forc3** [comment]
Apologies but I've just had a usb loss using wayland. Nothing in the log file generated. Again re-plug sorted the problem

**Comment by Blad3forc3** [comment]
You can close this Ruan. It was a failing power supply!

**Comment by ruanformigoni** [comment]
Thanks for letting me know @Blad3forc3 ! I hope nothing else got damaged.
