### ISSUE TITLE
EXE File not in the executable list to check if all uppercase

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#58]
Hi!

In gameimage, when you get to the executable file list to select before packing, if the executable name is all uppercase ie. RUAN.EXE it will not show up in the list to choose. If it's renamed to ruan.exe or Ruan.exe then it shows and is selectable

**Comment by ruanformigoni** [comment]
Fixed, it was an issue with the regex not being case-insensitive. Thanks!
