### ISSUE TITLE
Multiple EXES not selectable

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#59]
I have a game that install both the original version and the expansion to it at the same time. Is it possible to select both exes when telling the gameimage what exe to run so that it can automatically create a final file that lets you swap between games? At the moment it looks like you have to install the same file twice to run the expansion which wastes space

**Comment by ruanformigoni** [comment]
Hi @Blad3forc3 , currently it is not possible. I'll include a menu entry in the launcher to select another executable besides the default.

**Comment by Blad3forc3** [comment]
Sounds good Ruan. Just have to remember what the other exes are called.
An idea if you can add it to the launcher could it produce a list of exe files within the game folder so its easier to select?

**Comment by ruanformigoni** [comment]
> An idea if you can add it to the launcher could it produce a list of exe files within the game folder so its easier to select?

That's what I was thinking of implementing, like it was for the previous launcher.

**Comment by ruanformigoni** [comment]
Implemented in `v1.3.0`, you can configure this in the wizard:
![arguments-wizard](https://github.com/ruanformigoni/gameimage/assets/18180693/449f5140-5f9b-438b-8c32-90ba5861a776)

And also in the launcher:
![arguments-launcher-selector](https://github.com/ruanformigoni/gameimage/assets/18180693/6d4e4883-afa7-4813-849c-3361945bb6e3)

An executable list allows a different executable to be used before pressing play.
![arguments-launcher-cover](https://github.com/ruanformigoni/gameimage/assets/18180693/d3bed596-c9be-4031-bd86-6b582a7196d1)
