### ISSUE TITLE
Option to add parameters to exe file when run

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#60]
Hi,
Could there be an option add parameters after the exe has been chosen?
For example game.exe -xres=1920 -yres=1080

**Comment by ruanformigoni** [comment]
Hi @Blad3forc3, sure! I'll include this in the wizard & launcher.

**Comment by Blad3forc3** [comment]
Thanks Ruan, I have a few games that require parameters

**Comment by ruanformigoni** [comment]
One more thing, could you point me to a game & its required parameter so I can verify it works?

**Comment by Blad3forc3** [comment]
Diablo II. I'm trying to get the 3dfx mode to work (It does on the appimage version) with the gog version
nGlide needs to be installed within the flatimage too, 
https://www.zeus-software.com/downloads/nglide

Install the game then launch with game.exe -3dfx

**Comment by Blad3forc3** [comment]
Could there also be an option to prefix an exe. I have a game that i need to reduce the cpu core amount before it runs. The command i need to prefix the wine command is "schedtool -a 0x1 -e"

so the command to run would be 

schedtool -a 0x1 -e wine <path to exe>

**Comment by Blad3forc3** [comment]
Is there any file i can add a parameter to the exe in the flatimage setup?

**Comment by ruanformigoni** [comment]
Hi @Blad3forc3 , the boot file is a C++ generated binary, so that is not possible. There will be no need for that however:

![args-wizard](https://github.com/ruanformigoni/gameimage/assets/18180693/5924edeb-4916-49b8-b5ba-97fe6f1d5957)

You will also be able to change it in the launcher afterwards, it still needs a bit of testing however :smile:

**Comment by Blad3forc3** [comment]
Oh fantastic, Thanks Ruan

**Comment by ruanformigoni** [comment]
No problem. Feature released in `v1.2.0`

**Comment by Blad3forc3** [comment]
After trying the new gameimage the parameter is not being sent after the executable. In the log file it says no parameters

I :: Selected path_file_rom: "wine/drive_c/Program Files (x86)/Diablo II/Game.exe"
I :: Open file '"/media/ade/Temp/Temp/build/gameimage.json"' as READ
I :: [o] :: I :: Open file '"/media/ade/Temp/Temp/build/Diablo-II/gameimage.env.json"' as READ
I :: [o] :: I :: Could not set environment: Failed to open '/media/ade/Temp/Temp/build/Diablo-II/gameimage.env.json'
I :: [o] :: I :: FlatImage distribution: arch
I :: [o] :: I :: Open file '"/media/ade/Temp/Temp/build/Diablo-II/gameimage.json"' as READ
I :: [o] :: I :: Open file '"/media/ade/Temp/Temp/build/Diablo-II/gameimage.json"' as READ
I :: [o] :: I :: Open file '"/media/ade/Temp/Temp/build/Diablo-II/gameimage.wine.args.json"' as READ
I :: [o] :: I :: Optional (caught): Key 'wine/drive_c/Program Files (x86)/Diablo II/Game.exe' not present in db file
I :: [o] :: I :: **No arguments for "wine/drive_c/Program Files (x86)/Diablo **II/Game.exe"**
I :: [o] :: I :: [o] :: [wine.sh] Container   : arch
I :: [o] :: I :: [e] :: [wine.sh] /fim/mount/wine/bin/wine.sh: line 95: 35942 Killed                  wine "$@"
I :: [o] :: I :: [o] :: [wine.sh] Session Type: x11
I :: [o] :: I :: [o] :: [wine.sh] $*          : /media/ade/Temp/Temp/build/Diablo-II/wine/drive_c/Program Files (x86)/Diablo II/Game.exe
I :: [o] :: I :: [o] :: [wine.sh] HOME        : /media/ade/Temp/Temp/build
I :: [o] :: I :: [o] :: [wine.sh] WINEPREFIX  : /media/ade/Temp/Temp/build/Diablo-II/wine
I :: [o] :: I :: [o] :: [wine.sh] WINEHOME    : /wine/home
I :: [o] :: I :: [o] :: [wine.sh] glxinfo log : /media/ade/Temp/Temp/build/Diablo-II/wine/glxinfo.log
I :: [o] :: I :: [o] :: [wine.sh] GPU Vendor  : nvidia corporation
I :: [o] :: I :: [o] :: [wine.sh] GPU Device  : NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
I :: [o] :: I :: [o] :: [wine.sh] OpenGL      : 4.6.0 NVIDIA 550.78
I :: [o] :: I :: [o] :: [wine.sh] Vulkan log  : /media/ade/Temp/Temp/build/Diablo-II/wine/vulkan.log
I :: [o] :: I :: [o] :: [wine.sh] /fim/mount/wine/bin/wine
I :: [o] :: I :: [o] :: [wine.sh] Wine version: wine-9.7 (Staging)
I :: [o] :: I :: [o] :: [wine.sh] Switched directory to: /media/ade/Temp/Temp/build/Diablo-II/wine/drive_c/Program Files (x86)/Diablo II
I :: [o] :: I :: Finished Command: '/fim/mount/wine/bin/wine.sh /media/ade/Temp/Temp/build/Diablo-II/wine/drive_c/Program Files (x86)/Diablo II/Game.exe'
I :: Finished Command: '/media/ade/Temp/Temp/build/wine.flatimage fim-exec /media/ade/Temp/Temp/build/Diablo-II/boot'
Test finished without errors

**Comment by ruanformigoni** [comment]
Could you try pressing tab, or clicking on another field before pressing play? The field seems to register the parameters after you click out of it.

**Comment by ruanformigoni** [comment]
Fixed in [v1.2.1](https://github.com/ruanformigoni/gameimage/releases/tag/v1.2.1), it should not update properly as you type.

**Comment by Blad3forc3** [comment]
Works great now Ruan thanks very much!
Just a question, if i wanted to prefix a command to the exe could that be added using the environment variables?

Could i just put into the fields schedtool -a 0x1 -e and that would be executed just as a WINEDLLOVERRIDE is?

**Comment by ruanformigoni** [comment]
Glad that it works! Currently I have plans to include a configuration tab to select which (or how many) CPU cores to use. Modifying the launch command directly is currently not supported.
