### ISSUE TITLE
Extra Folder created when running flatimage

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#61]
Hi,

On certain games (not all) i get an extra folder created that isn't hidden called whatever the flatimage is called .config

I have attached a picture.
Is this normal?
![Screenshot_20240406_173501](https://github.com/ruanformigoni/gameimage/assets/39629883/40a52e26-34c2-44dc-93c7-0e25f374e90d)

**Comment by ruanformigoni** [comment]
Hi @Blad3forc3 , thanks for the report! I fixed this bug on the wine runner yesterday, you probably got the version previous to that.

You can fix this on the affected games with the command:
```
./"Star Wars Empire At War" fim-dwarfs-overlayfs usr '"${FIM_DIR_BINARY}"/."${FIM_BASENAME_BINARY}".config/overlays/usr'
```

**Comment by Blad3forc3** [comment]
Thanks Ruan. The flatimages i made today didnt exhibit this problem but all good now
