### ISSUE TITLE
Wine STaging updated Runner but when using gameimage it says version 9.5

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#66]
Has staging been updated to 9.6 as it is saying staging 9.5 in the log file?

**Comment by Blad3forc3** [comment]
Ok thanks Ruan :)

**Comment by ruanformigoni** [comment]
No problem. You can use the wine_url option to use the latest, grab the link from [here](https://github.com/Kron4ek/Wine-Builds/releases). E.g.: `https://github.com/Kron4ek/Wine-Builds/releases/download/9.6/wine-9.6-staging-amd64.tar.xz`
