### ISSUE TITLE
RPCS3 and DLC packages

### ISSUE THREAD

**Issue by jdwininger** [ruanformigoni/gameimage#7]
Is there any way to have RPCS3 install .pkg DLC packages after it installs the .PUP firmware files. I was reading the documentation and didn't find anything mentioning it.

If there is not currently a way to achieve this then I'd like to submit it as a feature request.

**Comment by ruanformigoni** [comment]
Hi @jdwininger , I haven't though about that, nice one, I'll look into how to implement it :)

**Comment by ruanformigoni** [comment]
In the project re-release, it is now possible to bundle DLC packages with RPCS3. :smile:
