### ISSUE TITLE
Option to change the main flatimage icon

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#72]
Can there or is there a way to change the flatimage icon after generating the flatimage without extracting the contents?
A couple of times i've selected a png image to use as the main icon in a multi game flatimage but it's chosen one of the icons from inside the flatimage

**Comment by ruanformigoni** [comment]
Hi @Blad3forc3 ! There is a way to do that, it is:
```
./my-game.flatimage fim-exec cp ./my-new.png /fim/desktop/icon.png
```
You will need to clear the icon cache on your desktop environment or rename the flatimage file, for it to update the icon.

**Comment by Blad3forc3** [comment]
Thanks Ruan. I'll give it a go later

**Comment by Blad3forc3** [comment]
Ive tried deleting the icon cache and renaming the flatimage but the icon doesn't get updated. I'm using kubuntu

**Comment by ruanformigoni** [comment]
That's odd, after copying the file what I do is to delete `~/.cache/icon-cache.kcache` and restart the file manager.

**Comment by Blad3forc3** [comment]
WHen i run the command i get this error

cp: cannot create regular file '/fim/dekstop/icon.png': No such file or directory

**Comment by Blad3forc3** [comment]
> That's odd, after copying the file what I do is to delete `~/.cache/icon-cache.kcache` and restart the file manager.

It seems theres something more sinister going on here.

Sometimes when i build a flatimage and select the desktop icon it reverts to a different icon from previously. Something with the cache file maybe

**Comment by Blad3forc3** [comment]
Just an update to this Ruan. I think i've sorted the problem. I had some leftover files that were collecting in the var/tmp folder all related to various flatimages i had created. I deleted them all and now the icon is sticking correctly

**Comment by ruanformigoni** [comment]
Hi @Blad3forc3 , thanks for the update. Glad it worked!
