### ISSUE TITLE
Each flatimage created produces a shortcut in the games folder main menu. Option to add one or not?

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#73]
Flatimage automatically adds a shortcut to the created flatimage in the games folder. Can we have it as an option to add one or not?

**Comment by ruanformigoni** [comment]
Hi @Blad3forc3 , you can currently disable this with `./my-game.flatimage fim-config-set desktop 0`. I'll consider adding it as an option after packaging the games.

**Comment by Blad3forc3** [comment]
Thanks Ruan. I didnt notice it at first until i opened my menu and saw a rack of shortcuts in my game folder. I can just delete them manually for now but it would be nice to have the option to add one or not

**Comment by ruanformigoni** [comment]
Desktop integration is now optional, you can choose to enable/disable after clicking on next in the creator menu.
