### ISSUE TITLE
bwrap error

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#74]
I am just trying the latest version and i am getting this error when trying to install dxvk into the flatimage

bwrap: Can't create file at //lib/libnvidia-gtk2.so.510.47.03: No such file or directory

 i dont undertand where this has come from as my driver version is 550.78

This is a clean build directory

**Comment by Blad3forc3** [comment]
The error has gone but the wineprefix is not created and dxvk doesnt get installed

this is the log after pressing install dxvk

I :: [o] :: [wine.sh] Container   : arch
I :: [o] :: [wine.sh] Session Type: x11
I :: [o] :: [wine.sh] $*          : winetricks dxvk
I :: [o] :: [wine.sh] HOME        : /media/ade/Temp/Temp/build
I :: [o] :: [wine.sh] WINEPREFIX  : /media/ade/Temp/Temp/build/Diablo-II/wine
I :: [o] :: [wine.sh] WINEHOME    : /wine/home
I :: [o] :: [wine.sh] glxinfo log : /media/ade/Temp/Temp/build/Diablo-II/wine/glxinfo.log
I :: [o] :: [wine.sh] GPU Vendor  : mesa
I :: [o] :: [wine.sh] GPU Device  : llvmpipe (LLVM 17.0.6, 256 bits)
I :: [o] :: [wine.sh] OpenGL      : 4.5 (Compatibility Profile) Mesa 24.0.6-arch1.2
I :: Finished Command: '/media/ade/Temp/Temp/build/wine.flatimage fim-exec wine.sh winetricks dxvk'
Frontend key is: 1092689078
I :: Open file '"/media/ade/Temp/Temp/build/gameimage.json"' as READ
I :: Open file '"/media/ade/Temp/Temp/build/gameimage.json"' as READ
I :: Open file '"/media/ade/Temp/Temp/build/gameimage.json"' as READ
I :: Open file '"/media/ade/Temp/Temp/build/gameimage.json"' as READ
I :: Open file '"/media/ade/Temp/Temp/build/gameimage.json"' as READ
I :: Open file '"/media/ade/Temp/Temp/build/gameimage.json"' as READ
I :: Open file '"/media/ade/Temp/Temp/build/gameimage.json"' as READ
I :: application: Diablo-II
I :: image: "/media/ade/Temp/Temp/build/wine.flatimage"
I :: prefix: "/media/ade/Temp/Temp/build/Diablo-II/wine"
I :: [o] :: [wine.sh] Container   : arch
I :: [o] :: [wine.sh] Session Type: x11
I :: [o] :: [wine.sh] $*          : uninstaller
I :: [o] :: [wine.sh] HOME        : /media/ade/Temp/Temp/build
I :: [o] :: [wine.sh] WINEPREFIX  : /media/ade/Temp/Temp/build/Diablo-II/wine
I :: [o] :: [wine.sh] WINEHOME    : /wine/home
I :: [o] :: [wine.sh] glxinfo log : /media/ade/Temp/Temp/build/Diablo-II/wine/glxinfo.log
I :: [o] :: [wine.sh] GPU Vendor  : mesa
I :: [o] :: [wine.sh] GPU Device  : llvmpipe (LLVM 17.0.6, 256 bits)
I :: [o] :: [wine.sh] OpenGL      : 4.5 (Compatibility Profile) Mesa 24.0.6-arch1.2
I :: Finished Command: '/media/ade/Temp/Temp/build/wine.flatimage fim-exec wine.sh

I also tried add remove programs to see if it would create a prefix but nothing straight to finished command

**Comment by ruanformigoni** [comment]
Try to run `export FIM_DEBUG=1` and then `./gameimage.run` to enable debugging for flatimage. This should show further details on what is going wrong.

**Comment by Blad3forc3** [comment]
I've attached the log file until i've selected to install dxvk

[log.txt](https://github.com/ruanformigoni/gameimage/files/15201926/log.txt)

**Comment by ruanformigoni** [comment]
I'm setting up an nvidia ubuntu install to test this, could you please check what results you get doing this?

https://github.com/ruanformigoni/gameimage/assets/18180693/186fd8c0-f688-459b-95bf-e861781e7582

**Comment by Blad3forc3** [comment]
I've done it on a previous flatimage i have created that works fine

Attached a log file whilst running ./Forsaken.flatimage fim-exec vkcube

[log.txt](https://github.com/ruanformigoni/gameimage/files/15204040/log.txt)

**Comment by Blad3forc3** [comment]
Thanks Ruan it seems to be working now
