### ISSUE TITLE
Opcode error

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#75]
Hi Ruan,
I'm afraid i'm going to have to report this error again.
When i preview a flatimage i get an opcode error randomly. I previously reported this as a power supply issue but it is happening only during the flatimage preview or when running a flatimage.
I dont have any problems running anything else

the error in the log is this

[wine.sh] X Error of failed request:  XI_BadDevice (invalid Device parameter)
I :: [o] :: I :: [o] :: [wine.sh]   Major opcode of failed request:  131 (XInputExtension)
I :: [o] :: I :: [o] :: [wine.sh]   Minor opcode of failed request:  3 (X_OpenDevice)
I :: [o] :: I :: [o] :: [wine.sh]   Device id in failed request: 0x5e00003
I :: [o] :: I :: [o] :: [wine.sh]   Serial number of failed request:  213
I :: [o] :: I :: [o] :: [wine.sh]   Current serial number in output stream:  213

and then refuses to run.
If i manually set the wineprefix to the prefix flatimage created and run it externally i do not get any problems

**Comment by ruanformigoni** [comment]
Hi @Blad3forc3 , no problem! Thanks for reporting this issue.

**Comment by Blad3forc3** [comment]
Close this Ruan, After getting a new PSU it turns out it was some broken USB ports on the motherboard

**Comment by ruanformigoni** [comment]
Thanks for the update! Closing.
