### ISSUE TITLE
Failed to verify and configure downloaded files

### ISSUE THREAD

**Issue by Blackfox-Thane** [ruanformigoni/gameimage#76]
I keep getting this error on gameimage when trying to verify the downloaded build files.

`Failed to verify and configure downloaded files
I :: SHA passed for "/home/thane/Games/Emulators/build/wine.dwarfs"
I :: key identifier: /home/thane/Games/Emulators/build/wine.dwarfs
I :: Generated message_queue key: 1090782383
I :: Message queue id: 32800
`

i'm also including this log file
[gameimage.log](https://github.com/ruanformigoni/gameimage/files/15399096/gameimage.log)

**Comment by ruanformigoni** [comment]
Hi @Blackfox-Thane, thanks for the bug report! This seems to be because `lsof` is missing. I'll include it in the next release, meanwhile you can install it with your distribution package manager or use [this](https://github.com/ruanformigoni/lsof-static-musl/releases/tag/12c2552).

**Comment by ruanformigoni** [comment]
`v1.3.1` released with lsof included

**Comment by Blackfox-Thane** [comment]
Wow thank you for the quick response, and i just tried it and it worked also sorry for my late response

**Comment by ruanformigoni** [comment]
No problem! Thanks again for bringing this to my attention :smile:
