### ISSUE TITLE
Halo Combat Evolved Access Error

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#78]
When packaging wine and halo combat evolved in gameimage the resulting gameimage produces an error that it cant write / read from my documents. After installing msxml4 during setup this works fine during the preview in gameimage but the resulting flatimage errors out

Just an update. Another game suffers from this.

Godfather II errors during the preview just after the titles complaining it cant find the profiles that are stored in the my documents folder.
If i run it bypassing gameimage it runs fine.
Could be an access problem when using my documents?

**Comment by ruanformigoni** [comment]
Thanks for reporting this issue @Blad3forc3 , currently I do not know why this would happen. Will investigate.

**Comment by Blad3forc3** [comment]
Thanks Ruan. Seems to be some kind of access error when my documents is involved. For the record the appimage works fine

**Comment by Blad3forc3** [comment]
Another game Messiah complains it cant read a file from the games install directory but runs fine from an old appimage. The Game is available on GoG

**Comment by Blad3forc3** [comment]
I am getting a few games that run when previewed or run from their own prefix but when packed into a flatimage error out.
 Beyond Divinity is one that complains of accessing map 0 when run from a flatimage but this error doesnt exist during preview

**Comment by Blad3forc3** [comment]
Divine Divinity has the same problem. Works fine in preview, doesnt run in the built flatimage

**Comment by Blad3forc3** [comment]
Batman Arkham Knight works fine in a preview but the gameimage doesnt run complaining of an I/O error on files to run.
I've tried creating the flatimage three times and each time the game runs when previewed in gameimage but the resulting flatimage fails

**Comment by Blad3forc3** [comment]
Wing Commander III when running through dosbox using wine complains of an error creating the swapfile and not running in a flatimage. When creating the flatimage and running the preview it runs fine.
I think there must be write issues around the c drive with certain games after the flatimage is created with wine

**Comment by ruanformigoni** [comment]
Hi @Blad3forc3 , thanks a lot for the analysis! I'll try to replicate from my side :smile:

**Comment by Blad3forc3** [comment]
No problem Ruan.
I have investigated another game with this problem.
A game called Codename Eagle complains that it cant access certain files when made into a flatimage (even though the preview worked fine during creation) 
What i have found is if i put all the game files in to location .Codename-Eagle/upperdir/wine/drive_c/*wherever the game is installed dir* then the game will run from the flatimage, so there is definitely a read/write issue going on

**Comment by Blad3forc3** [comment]
Just an update on this. I am getting a lot of  games that error out in a flatimage after running ok in the preview. They seem to point to a read/write issue in the my documents folder / c drive in general. A tough one to pinpoint but some of them correspond to making an old appimage when the actual games files were stored in the hidden folder and not in the appimage itself

**Comment by ruanformigoni** [comment]
Hi @Blad3forc3,  Let me know if this is still an issue with the current version of gameimage

**Comment by ruanformigoni** [comment]
Hi @Blad3forc3 , I'm going to assume this is fixed. If it is not, please re-open this issue, thanks!
