### ISSUE TITLE
Misclassification of GPU by "Tomb Raider: Anniversary"

### ISSUE THREAD

**Issue by Tell-Sackett** [ruanformigoni/gameimage#79]
Hardware and Environment:
- Debian 12 "Bookworm"
- Cinnamon desktop environment
- X11
- Nvidia Geforce RTX 2070 Super
     - Proprietary Drivers
     - (*) including i386 drivers

Steps to Reproduce (performed throughout all of my testing):
- Downloaded GOG backup installers for "Tomb Raider Anniversary"
- Launched gameimage.run (v1.3.1)
- Chose "wine-default" options
- ...for each attempt at packaging the game, further steps are detailed below

Problem (tldr):
- Upon launching "tra.exe", "Tomb Raider Anniversary" provides the user with an options menu. Here, you are given the option to change a few graphical settings, etc. Part of this menu allows you to choose your graphics card model (from a list of detected card(s), presumably). However, I am only given the option of an "Nvidia GTX 470". Upon applying these settings, the game is automatically launched. The framerate was bad enough that, even though I was able to make it to the main menu, I was hardly able to align my cursor with the "[Quit to Desktop"] option, and upon clicking it, gave up waiting for the confirmation menu to properly show-up in a clickable form. This is in contrast to the game, when installed via Lutris, being able to properly identify my card as an RTX 2070 Super and playing at a very smooth fps.

Problem (testing detailed summary):
1. The process of attempting to create a flatimage of TRA was done over the course of two computer sessions, spanning two days. During both sessions the same situation with the GTX 470 occured. (*) During the first session, I attempted to perform this process, I believe, without proper proprietary Nvidia i386 drivers. During this first session I was able to download DXVK (as well as the other addon), but upon trying to either install or launch the game (apologies, I can't recall which, exactly), the process would fail, with a message stating that the game does not support DirectX12, and that I should not use the "-dx12" or "[-dx??]" (sorry, I can't remember the exact error message) flags when launching. Seeing as how I was not inputting these arguments to begin with, I reattempted the process, this time not installing "DXVK 9/10/11" or the other addon option. If I recall correctly, during these attempts, the process would fail, stating that the game required the use of Directx9. I then used the flag "-dx9" in the argument section of the executable and the game launched. However, the GTX 470 and framerate issues were present.
2. After installing additional proprietary Nvidia i386 drivers, I got the idea of trying to run the game through Lutris. Here, after downloading the game, I was prompted with the option to launch the options menu, or the game directly. Upon choosing the options menu, I was provided with the my actual graphics card (an Nvidia RTX 2070 Super). After applying the settings, the game launched and ran very smoothly.
3. My second attempt at packaging TRA as a flatimage was done after the Lutris testing (now with the i386 drivers). The first time, I tried to download DXVK 9/10/11. However, this process seemed to hang and would not complete. After a while, I closed gameimage and attempted another round. This second time, I couldn't even get to the DXVK page. I closed the application and tried again. This third time, I made it to the DXVK page, and upon attempting to download DXVK 9/10/11 and the other add-on, they both completed very quickly (too quickly, in fact). Upon trying to proceed to the next page, I had some more issues. After a while I came to the conclusion that during my first attempt during this session (when the application hung on the DXVK download), some processes never completed and were complicating further attempts at using the application. I went into my Process Monitor application and, indeed, found some processes still attempting to run. After killing these, I tried to package the game once more, again trying to install DXVK 9/10/11. This process ended the same as the first time this session, with the application hanging and resulting in me having to kill the orphaned processes running in the background. The last attempt I made before writing this went as follows: I went through the process again without attempting to install DXVK 9/10/11, the other add-on, making any other wine configurations, etc.; launched "tra.exe" (with no additional arguments), and was greeted with the options menu where I was only given the option of choosing a GTX 470. After applying my settings the game automatically ran, and it had the same framerate problem I was having during my first session (before installing the i386 drivers).

Additional Notes:
- Apologies in advance for some of the vague terminology and lack of detail (as well, perhaps, as some misremembered details), this all took place over the course of two days, I did not take proper notes, and it is currently very late where I am. If additional testing regarding this issue is desired, please let me know what to try and I will do what I can.
- My main reason for posting this Issue is less to have this particular problem fixed and more to, hopefully, shed light on a particular problem that might provide insight as to how the code / project might could be improved on a broader scale (particularly regarding GPU recognition, if such is a widespread issue with GameImage).
- Finally, I apologize if I'm, in some way, being improper by posting this here or am not following certain understood guidelines of posting here; I'm still learning such GitHub community standards.

Thanks

**Comment by ruanformigoni** [comment]
Hi @Tell-Sackett , thanks a lot for the detailed information on this issue! Always feel free to post problems that you find doesn't matter how small they might seem to be.

Let's try to determine why the game is running poorly, it could be because dxvk is not installed properly or because the GPU drivers are not properly detected by flatimage (and using the integrated graphics instead). 

By default you should install dxvk to avoid using the default opengl wine backend which much slower, you can check if the game is running with dxvk by adding the environment variable `DXVK_HUD` with the value `full`, like this:

<img src="https://github.com/ruanformigoni/gameimage/assets/18180693/a5e0ff09-58d9-46dc-a6b0-9c3bc286fcd5"  width="300"/>

And then running the game with dxvk installed, which should show up like this:

<img src="https://github.com/ruanformigoni/gameimage/assets/18180693/ef466280-8c3a-4fed-9301-ec1588bdd70e"  width="300"/>

It already shows you the graphics adapter being used to run the game, it is normal for the dxvk process to stall without any output for some time (this is done by winetricks, not gameimage). Try to restart the process with a clean build directory (remove the previous one).

If it is still not possible to use dxvk, try to create the image anyway (where it is running in a sluggish manner) and open in the terminal like this:

```bash
FIM_DEBUG=1 ./tomb-raider.flatimage
```

This would output information about the GPU bindings as well as the currently selected one, if possible try to post it here so I can take a look.

**Comment by Tell-Sackett** [comment]
Here is a summary of the process I performed, including the results. Relevant .txt files, containing terminal and log output are attached as well.

Attempt 1 (installed DXVK, set environment variable "DXVK_HUD" "full" on, as well as attempting with them off):

- used clean gog backup installers, new cover-art jpeg's, a new copy of the gameimage executable, and a new working directory (which was where I planted the "build" directory)
- wine, default
- Configure Wine step:
	- installed DXVK (took ~1 minute)
	- no other options used
- gog installer completed successfully
- did not launch game at gog installation screen or "Install/Test the Application(s)" screen
- flatpak was created successfully
	- see [attempt_1_logger.txt](https://github.com/ruanformigoni/gameimage/files/15494128/attempt_1_logger.txt) for complete logger output for the packing process
	- see [attempt_1_terminal_install.txt](https://github.com/ruanformigoni/gameimage/files/15494141/attempt_1_terminal_install.txt) for complete terminal output for the packing process
- launched flatimage and set "Environment Variables": "DXVK_HUD" and "full"
- game failed to launch: flatimage main menu went grayscale but returned to color not long after
	- see [attempt_1_terminal_play_1.txt](https://github.com/ruanformigoni/gameimage/files/15494150/attempt_1_terminal_play_1.txt) for terminal log since launch of the newly created flatimage
- attempted to run again with the same result
	- see [attempt_1_terminal_play_2.txt](https://github.com/ruanformigoni/gameimage/files/15494156/attempt_1_terminal_play_2.txt) for full terminal since the first launch of the newly created flatimage
- removed set "Environment Variables"
- attempted to run again with the same result
	- see [attempt_1_terminal_play_3.txt](https://github.com/ruanformigoni/gameimage/files/15494161/attempt_1_terminal_play_3.txt) for full terminal since the first launch of the newly created flatimage
- closed the flatimage and ran it again without the terminal
- set the above-mentioned environment variables
- attempted to run the game again with the same results as above
- closed the flatimage, relaunched it again
- attemted to launch the game without setting the environment variables to the same result
- preserved flatimage, and two config folders within "attempt_1" directory for further analysis if desired

Attempt 2 (did not install DXVK):

- used the same gog backup installers and the same cover-art jpeg's but trashed "Attempt 1"'s "build" directory
- wine, default
- Configure Wine step:
	- did not install/use any of these options
- gog installer completed successfully
- did not launch game at gog installation screen or "Install/Test the Application(s)" screen
- flatpak was created successfully
	- see [attempt_2_gameimage_logger.txt](https://github.com/ruanformigoni/gameimage/files/15494204/attempt_2_gameimage_logger.txt) for complete logger output for the packing process
	- see [attempt_2_terminal_install.txt](https://github.com/ruanformigoni/gameimage/files/15494206/attempt_2_terminal_install.txt) for complete terminal output for the packing process
- flatimage launched successfully, did not set any environment variables
- game launched into "Tomb Raider: Anniversary - Setup" menu
	- Display Adapter option(s):
		- NVIDIA GeForce GTX 470
	- Resolution option(s):
		- 1024 by 768 (this was the option that was used by default)
		- many other options, including my monitor resolution
	- Refresh Rate option(s):
		- 60
		- 50
		- no other options were given, despite (if I recall correctly) being given other options during the successful attempt performed two days ago via Lutris
	- Other options that probably aren't relevant
- game was performing terribly, had to "End" the process "tra.exe" from within my system monitor
	- see [attempt_2_terminal_play_1.txt](https://github.com/ruanformigoni/gameimage/files/15494207/attempt_2_terminal_play_1.txt) for terminal log since launching the newly created flatimage of "Attempt 2"
- closed the flatimage menu
- executed the flatimage from the terminal with the command "FIM_DEBUG=1 ./Tomb-Raider-Anniversary.flatimage"
- flatimage menu opened successfully
- game ran sluggish, had to "End" process "tra.exe" from system monitor
- closed the flatimage menu
	- see [attempt_2_terminal_play_2.txt](https://github.com/ruanformigoni/gameimage/files/15494208/attempt_2_terminal_play_2.txt) for terminal log only since launching with the command "FIM_DEBUG=1 ./Tomb-Raider-Anniversary.flatimage"
- preserved flatimage, and two config folders within "attempt_2" directory for further analysis if desired

Attempt 3:

- copied the flatimage from Attempt 1 (the flatimage successfully created with DXVK) into a new directory
- executed with the command "FIM_DEBUG=1 ./Tomb-Raider-Anniversary.flatimage"
- set the environment variables "DXVK_HUD" and "full"
- attempting to launch the game resulted in the same results as "Attempt 1"
	- see [attempt_3_terminal_play_1.txt](https://github.com/ruanformigoni/gameimage/files/15494210/attempt_3_terminal_play_1.txt) for terminal log of "Attempt 3"
- preserved flatimage, and two config folders within "attempt_3" directory for further analysis if desired

I think that covered everything.

**Comment by ruanformigoni** [comment]
Thanks a lot for this information, and sorry for the troubles. I have identified the issue, the nvidia drivers are no being properly bound to the container, you can see this by these two lines:
```
I :: [o] :: [wine.sh] GPU Vendor  : mesa
I :: [o] :: [wine.sh] GPU Device  : llvmpipe (LLVM 17.0.6, 256 bits)
```
I will setup a debian/nvidia system to try to re-create the issue from my end. Your attempt 2 works probably because the integrated graphics supports opengl and does not suport vulkan.

**Comment by Tell-Sackett** [comment]
Np, and thank for identifying the issue! I glanced at the outputs but was unable to understand what was being said due to my, still very limited, knowledge on this kind of thing.

In case it helps:
I just recently distro-hopped to this from a well-maintained Arch spin (it's my first time running base Debian), so I hope this isn't all just a result of my incompetence in driver installation and management. I attempted to follow (and presumably succeeded in, as the "NVIDIA Settings" app is installed and functioning properly) the guide on Debian's official site for replacing the stock Nouveau drivers for Bookworm with the proprietary Nvidia ones. Of particular note are sections: [1.2.2.2](https://wiki.debian.org/NvidiaGraphicsDrivers#Debian_12_.22Bookworm.22) for Bookworm proprietary driver installation, [1.8.4](https://wiki.debian.org/NvidiaGraphicsDrivers#Miscellaneous) for replacing the Nouveau drivers, and (this last section was only followed during the middle of my first post, as noted) [1.2.3](https://wiki.debian.org/NvidiaGraphicsDrivers#Installing_32-bit_libraries_on_a_64-bit_system) for 32-bit driver libraries installation.

**Comment by ruanformigoni** [comment]
I've managed to replicate the issue on my side, it should be all fixed now. The issue was that some nvidia files on debian are symlinks to `update-alternatives`, so I just needed to reference that to the real file before creating a symlink from inside the container. The driver installation for my side required to run the command `sudo nvidia-xconfig --egpu` [doc](https://manpages.debian.org/testing/nvidia-xconfig/nvidia-xconfig.1.en.html#egpu), because I'm using a thunderbolt one.

Start up with a clean build directory, re-download the files and that should do it.

**Comment by Tell-Sackett** [comment]
Sorry for the late response. I've been out of the house for a number of days now, and will not be back for at least another week (probably longer); sorry about that, some life stuff is going on. For reference once I _do_ get back: I have not seen an update to the program since you made your last post; what files, exactly, should I move or symlink where?

**Comment by ruanformigoni** [comment]
No problem, no need to hurry. You shouldn't need to change anything, I updated the runners with the changes (the files you download in the fetch screen). So just starting fresh and building a project from scratch should work.

**Comment by Tell-Sackett** [comment]
Sorry for the long wait; lots of irl life changes.

Just tried it out: the game recognized my GPU, monitor refresh rate, AND ran buttery smooth!

Thanks soo much!
