### ISSUE TITLE
Skyrim GOG

### ISSUE THREAD

**Issue by wubbs37** [ruanformigoni/gameimage#8]
Trying Skyrim AE GOG version. Going through the installer seems fine, game runs and plays up to the the point of trying ./AppRun 

$ ./AppRun
cp: cannot stat '/app/wine': No such file or directory

After it's built, It extracts basically the entire game and returns

$ ./Skyrim_Ae-x86_64.AppImage
/tmp/.mount_Skyrimgs1req/AppRun: line 38: /tmp/.mount_Skyrimgs1req/usr/bin/wine:
No such file or directory

Assuming this is user error but I'm not sure what I did. Installed xact with winetricks for sound issues, and that's really about it. Let the script use defaults for the most part otherwise.

Edit: On arch linux

Edit2: I guess trying to use mo2 was my issue.

**Comment by wubbs37** [comment]
Not using mo2 fixed it. Feature request? Not even sure if it's possible.

**Comment by wubbs37** [comment]
I was completely overthinking it.
enable wine-mono
winetricks cmd
winetricks vcrun2015
winetricks xact_x64

dump the contents of skse64.7z into skyrim root directory
same for mo2.7s (don't use a folder, use skyrim install directory as mo2 portable root directory)

test skyrim launcher, set your default graphics options, boot into wagon scene, create inis
test mo2 launcher.exe
use global instance
create and set all directories except base dir and profiles directory to a folder in c:\users\user\documents\my games\Skyrim Special Edition GOG
create and set profile directory to c:\users\user\appdata\local
done here

will throw an error and use "microsoft" profile by default. this is fine.
change active profile to Skyrim Special Edition GOG (This must always be your profile. MO2 just doesn't like using gog's proper folder to write loadorder files to even on windows- this is a workaround)
close mo2
quit gameimage
restart gameimage, do not overwrite anything, just continue up to where you were before
build and test. ./AppRun won't work before you build the appimage itself, but it should once you're done.

**Comment by wubbs37** [comment]
If you're using a steam version, or if/when mo2 ever fixes the profiles issue, that step should in theory follow the same steps as the other mo2 paths

**Comment by wubbs37** [comment]
When you run it under a username under the one you created it under, you're gotta reset the paths in mo2 and copy the files over from the hidden directory next to the appimage

**Comment by ruanformigoni** [comment]
Hi @wubbs37, I'm glad you figured it out! Sorry for the late reply, anything else feel free to ask.
