### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by MRDeu** [ruanformigoni/gameimage#82]
First of all congratulate you for this format, I love it.

1 - Would it be possible to add an auto-launch mode? If you launch an application from a frontend or Steamdeck, it would be nice to force its execution without the menu that comes up initially.

2 - Could you create a refresh option to select the executable of the games that are added without prior installation? It would be very useful for games that are simply distributed in a compressed file. t would also be nice to be able to choose an executable other than *.sh.

3 - Would it be possible to reduce the space of Wine or add other Proton available via Port Proton or Proton-UP QT?  Sometimes with some games the file size increases a lot.

4 - Many people launching the game from the SteamDeck Game mode find that the controls do not work, but if they launch the application from the desktop everything works normally, could something be done to improve compatibility or is it a Deck launcher thing?

Keep up the good work, I love this software.

**Comment by Tell-Sackett** [comment]
I can't offer much in the way of help, but I will say the following:
1. There is a way to bypass it by means of a flag that you pass. I don't remember where  or when you pass it though, nor what the flag is/was (it was specified in the documentation back when the project was CLI-based).

2. As far as running native Linux games is concerned, I concur with the *.sh request; being able to package files with the *.x86_64 file extension would be nice as well. Additionally, being able to select Windows shortcut files for Wine games would be ideal (some GOG games use a shortcut file to launch games, for example).

3. The option to adjust compression levels was available and documented when the project was CLI-based, but I don't know how to access this now that the project is GUI-based.

**Comment by ruanformigoni** [comment]
Greetings @MRDeu, thank you for your feedback! To answer your questions:

1. Auto launch is possible, but that would be a bit tricky with multiple games on the same image. Lets say you have three games on the same image, how one would create a launch icon from the deck UI that launches that specific game from the image? I think the simplest solution would be to work with a launch flag that references the game index, for example, if the image contains tomb-raider-anniversary,tomb-raider-legend,tomb-raider-underworld, you could create an entry in the deck UI with the command `./tomb-raider.flatimage --gameimage-index=0` to launch tomb raider anniversary or  `./tomb-raider.flatimage --gameimage-index=1` to launcher tomb raider legend and so on... What do you think of this solution?

2. Yes, that is on the works, I'll give two options in the installer (copy file(s) or install from file). There is a workaround to use it for any linux file (non-installable). Assuming the name of your game is tux, when you get to the "Install the Application" screen (where it gives the 'no .sh file was found), you can go to the folder `build/tux` and create a new folder called linux, inside this folder drop the "non .sh" file you want to use and rename it to end with ".sh". You should now be able to click on next and select this file as the default one to launch.

3. The size overhead comes greatly from the included mesa, radeon and intel drivers. I could make a lightweight alternative selectable from the wizard, that always binds the host drivers instead, however this would not be as portable, specially on non-gnu systems (the current gameimage works on alpine using the included gnu drivers which alpine does not have to bind into the container).

4. That's something I really want to improve, but I don't have a steam deck to try it on currently.

Thanks for the compliments, that means a lot. I appreciate that you found it useful :smile: 

Greetings @Tell-Sackett , thank you for your feedback also! To answer your questions:

1. This should be addressed by the (1).

2. Here you could use the workaround on (2). I find that it wouldn't trivial at the moment to work with windows shortcut files, but any executable should work.

3. I opened #83 to track the progress on this :smile:.

**Comment by cchulo** [comment]
for 1 it would be great if we could assign an alias and then use this alias to select the game via the launch options

**Comment by ruanformigoni** [comment]
> 2. Could you create a refresh option to select the executable of the games that are added without prior installation? It would be very useful for games that are simply distributed in a compressed file. t would also be nice to be able to choose an executable other than *.sh.

Implemented in `v1.4.0`, you can open the file manager and manually copy files.

![scr0](https://github.com/user-attachments/assets/cfa1abad-cf73-453e-bf5a-816a82f2309a)

Now all files are shown, you can filter them by name:

![scr1](https://github.com/user-attachments/assets/44349cc2-c02f-416c-a808-15af983d11c3)

> 3 - Would it be possible to reduce the space of Wine or add other Proton available via Port Proton or Proton-UP QT? Sometimes with some games the file size increases a lot.

I Have integrated GameImage with UMU launcher and Proton-GE. It is also now the default.

**Comment by ruanformigoni** [comment]
Lastly for this issue, it is now possible to launch games directly through id. More details [here](https://github.com/ruanformigoni/gameimage?tab=readme-ov-file#cli). Thanks!
