### ISSUE TITLE
FlatImage GUI launcher disable

### ISSUE THREAD

**Issue by UserName-Null0** [ruanformigoni/gameimage#85]
Hello, I was wondering if there's a way to disable the GUI Window that appears when launching a FlatImage and load directly into the program. The window is unnecessary for the use cases of my Flatimages and I am unable to access the versions of this program prior to the GUI being the default. Any and all help with this will be greatly appreciated!

**Comment by ruanformigoni** [comment]
Thanks for reporting this usability gap @UserName-Null0 ! I will update this issue when there are updates on the matter.

**Comment by ruanformigoni** [comment]
I'll test it on batocera as well. Thanks for that info!

**Comment by MRDeu** [comment]
> If there is an option to load directly a program like mentioned in [issue#82](https://github.com/ruanformigoni/gameimage/issues/82#issuecomment-2185259346) it'l be awesome. Right now i'm trying flatimages on Batocera pc and it works, the game start properly when it's started outside of EmulationStation frondend. I can even build the image on batocera, albeit slowly (the GUI itself is slow under Batocera, the image builds quickly). But when i try to start from ES it doesn't work and i think its because it cant start or display the flatimage gui window.

How did you launch a flatimage on Batocera?

Do u use an .sh? Can you share the code?

Thanks.

**Comment by Prommko** [comment]
I just downloaded gameimage.run, in the file browser right click on the file, properties and in permissions tab set all to everyone. Then just started the file from the file browser, from there followed the video tutorials. But the ui is very slow, click next and wait 10 sec or more.
After the image is ready you can start it and play the game from the file browser.
But in ES frontend it doesn't work (following the batocera wiki for ports category), if i could start the game directly i think it would work.

**Comment by ruanformigoni** [comment]
It is now possible to launch games directly through id. More details [here](https://github.com/ruanformigoni/gameimage?tab=readme-ov-file#cli). Thanks!
