### ISSUE TITLE
GUI Terminal Printout Extremely Slow

### ISSUE THREAD

**Issue by wubbs37** [ruanformigoni/gameimage#9]
Tried on multiple distros (Endeavous, Manjaro, Mint, Bodhi, Ubuntu) , terminal printout is slow on all of em.

Thinkpad X13 Gen 1 AMD 8 GB (Do I just not have enough RAM?)

**Comment by ruanformigoni** [comment]
Hi @wubbs37, thanks for the report! This issue is related on how the characters are currently printed in the terminal, it does not relate to hardware requirements. I'll try to improve it.

**Comment by ruanformigoni** [comment]
@wubbs37, this should be better in version `0.4.3`.
