### ISSUE TITLE
[Bug] The automatically created mime for the flatimage file blocks service menu for .flatimage files

### ISSUE THREAD

**Issue by malnaanah** [ruanformigoni/gameimage#99]
I have a KDE service menu for .flatimage files; however, mime files are created automatically for each flatimage file and that disable my service menu for that flatimage file. Is there a way to disable automatic creation of mime file for flatimages. Also, I think they are necessary and clutter the system.

Best regards.

**Comment by ruanformigoni** [comment]
I implemented it in this commit 55a17cc21029be8d7f1c6350abf57b3f55eb718f , you should be able to disable them in the next release :smile:

**Comment by malnaanah** [comment]
When do you expect the next release to be released?

**Comment by ruanformigoni** [comment]
Probably next week

**Comment by ruanformigoni** [comment]
Desktop integration is now optional, you can configure it after clicking on next in the creator screen.
